#!/usr/bin/env node
/**
 * The Terraform stack, checked with no credentials and nothing on the network.
 *
 * `infra/` provisions the bundle store, and the two things that can be wrong with it are
 * not the same shape. One half is whether the configuration is well formed and says what
 * it means to say, which is answerable from the files alone. The other is whether the
 * applied account matches what is written here, which needs credentials. This is the first
 * half, and it is the only half that can be a row in `pnpm verify` and therefore in CI:
 * `check:stack` is the credentialled one and is deliberately off the ladder, because a row
 * that cannot run reports NOT RUN, NOT RUN fails the run, and most machines here hold no
 * AWS profile.
 *
 * ## Why the first row is plain JavaScript
 *
 * `terraform` is not on the ubuntu-24.04 image that `ubuntu-latest` resolves to, and it is
 * not on every laptop, so three of these four rows can honestly report SKIPPED. If all four
 * could, a machine without the binary would get a report in which nothing ran, and a run of
 * nothing but SKIPPED rows still exits 0. That is the state `scripts/lib/report.mjs` exists
 * to refuse, so the invariants row reads the `.tf` files as text and as structure and needs
 * no binary at all.
 *
 * It is also the row carrying the assertions terraform has no opinion about. A lifecycle
 * expiration rule, a variable with no description and a trust policy condition spelled
 * `StringEqualsIfExists` all validate cleanly, and the last of those grants where it was
 * meant to deny.
 *
 * ## Why every count is measured from the disk
 *
 * `terraform validate -json` emits `{format_version, valid, error_count, warning_count,
 * diagnostics}` and nothing else, so a passing run names no file and a count taken from its
 * output is zero on exactly the runs that pass. `terraform fmt -check` prints only the files
 * that are wrong, which is the same problem. So each count below comes off the tree:
 * formattable files for `fmt`, declared `resource` blocks for `validate`, declared `run`
 * blocks for `test`, and evaluated assertions for the invariants.
 *
 * ## What the spawns are allowed to do
 *
 * `fmt` needs no init, no network and no credentials. `validate` and `test` need a prior
 * `terraform init`, which needs the network to fetch the provider and nothing afterwards.
 * `.github/workflows/ci.yml` runs `init -backend=false` for exactly that reason and this
 * script never runs one itself: an init from inside a guard would make the guard the thing
 * that downloads a 778 MB provider on a machine that did not ask for it. Without
 * `infra/.terraform` those two rows report NOT RUN naming the command, which fails the run
 * and says what to do about it.
 *
 * `CHECKPOINT_DISABLE` is set on every spawn. Without it terraform calls HashiCorp on
 * startup to ask whether it is out of date, so a guard advertised as needing no network
 * would make one request per row and print an upgrade notice into the middle of a report.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, realpathSync, statSync } from 'node:fs';
import { delimiter, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { check, notRun, render, skipped } from './lib/report.mjs';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));

/** The stack, relative to the repository root. */
const INFRA = 'infra';

/**
 * The invariants row, carrying the ids of the assertions it evaluated.
 *
 * The list rides on the row rather than living in a module-level export because the row is
 * what every caller already holds. A mutable export would be read by whichever test ran last
 * rather than by the run that filled it, and the ordering bug that produces is invisible: the
 * table would still be checked in both directions, just against somebody else's run.
 * `render` reads only the documented fields, so the extra one prints nowhere.
 *
 * @typedef {import('./lib/report.mjs').CheckResult & { arms: string[] }} InvariantsResult
 */

/** The publish workflow template the branch cross-check reads. Tracked in this repository. */
const WORKFLOW_TEMPLATE = 'kit/src/templates/workflow.ts';

/**
 * The extensions `terraform fmt` actually formats: configuration, variable definitions,
 * test files and mock data. Deliberately not every `.hcl` file.
 *
 * `.terraform.lock.hcl` is the one that would otherwise creep in, and it is not a format
 * target: fmt skips hidden files, and it is generated by terraform rather than written by
 * hand. Counting it as a file fmt could have examined would put a number in the row that
 * fmt was never going to reach, and the git cross-check below would then need an exception
 * for it, which is the shape of exemption this repository refuses.
 */
const FMT_EXTENSIONS = ['.tf', '.tfvars', '.tftest.hcl', '.tfmock.hcl'];

/**
 * Lifecycle actions that remove data, as HCL block or argument names.
 *
 * This is the sharpest single assertion in the file. S3 Lifecycle is the one mechanism that
 * ignores the bucket policy entirely: AWS states that "even if your bucket policy denies all
 * actions for all principals, your S3 Lifecycle configuration still functions as normal". So
 * an expiration rule is the one edit that empties a store whose every other control refuses
 * every delete, and it is a delete that `DenyObjectDeletion` cannot see. `bucket.tf` says the
 * same thing in prose and prose fails nothing.
 *
 * The pattern also catches `noncurrent_version_transition` and anything else whose name ends
 * in one of the two words, because the family is what matters rather than the four spellings
 * that exist today. It does not catch `transition_default_minimum_object_size`, which moves
 * nothing and is a legitimate argument, because the name has to end at the matched word.
 *
 * Two spellings of the name, and the second is the closure argument rather than a courtesy.
 * A nested block's name is otherwise always the first token on its line, and that is terraform's
 * own rule rather than a formatting habit: `rule { expiration { days = 30 } }` is refused with
 * "To define a nested block, place it on a line of its own within its parent block". The
 * attributes-as-blocks form `expiration = {` puts the name at the start of a line too and is
 * matched by the second arm. The one construct that writes it anywhere else is
 * `dynamic "expiration"`, which puts it in a quoted label after a keyword, and that is ordinary
 * Terraform rather than a contortion: a rule made conditional on a variable is the commonest
 * reason to reach for `dynamic` at all. Measured before this arm existed, a real
 * `aws_s3_bucket_lifecycle_configuration` whose rule carried `dynamic "expiration"` gave four
 * PASS rows, while the same rule written plainly went red.
 */
const DESTRUCTIVE_LIFECYCLE =
	/^[ \t]*(?:dynamic[ \t]+")?([a-z_]*(?:expiration|transition))(?:"[ \t]*\{|[ \t]*[{=])/gm;

/**
 * What each rendered policy document has to say, in order.
 *
 * `infra/tests/policies.tftest.hcl` asserts far more than this against the rendered JSON,
 * including the condition operators and the exact resource ARNs, and it is the better check.
 * It also needs terraform. This is the text-level backstop that still runs on a machine with
 * no binary, and text level is all it claims to be: it reads the `sid` arguments out of the
 * source, so it would not notice a statement whose effect or resource changed.
 *
 * The value of it at that level is real, because a statement deleted from one of these
 * documents is invisible in every other way. There is no plan diff, no warning and no error,
 * and the only thing that would ever notice a missing `s3:DeleteObjectVersion` is somebody
 * deleting a published bundle.
 *
 * Every `aws_iam_policy_document` in the stack, and the key set is cross-checked against the
 * documents parsed off the disk in both directions below. A hand table naming three of the
 * four was the state this file shipped in: `reader` was uncovered, a fifth document added
 * tomorrow would have been uncovered too, and neither absence could fail anything, which is
 * the same reasoning `REQUIRED_DIRS` in `scripts/lint.mjs` already carries.
 */
const POLICY_DOCUMENT_SIDS = {
	bundles: [
		'DenyInsecureTransport',
		'DenyUnconditionalObjectCreation',
		'DenyObjectDeletion',
		'DenyReplicationIntoStore',
		'DenyStoreReconfiguration',
	],
	publisher_trust: ['GitHubActionsOnOneBranchOfOneRepository'],
	publisher: [
		'ListOwnProjectPrefixes',
		'ReadOwnProjectPrefixes',
		'WriteOnceIntoOwnProjectPrefixes',
		'DenyEverythingElse',
	],
	reader: ['ListBundles', 'ReadBundles'],
};

/**
 * The documents `infra/tests/policies.tftest.hcl` is required to name, which is not all of
 * them.
 *
 * The table above has two jobs and they do not have the same membership. One is the Sid
 * expectation per document, which every document should carry. The other is the
 * every-statement-is-claimed-by-a-test scan below, and `reader` is outside that one because no
 * run block asserts anything about it today. Nothing prevents one: the document renders at plan
 * exactly as the other three do, so run blocks for it are a few lines in the same shape as the
 * ones already there, and writing them is the better fix rather than lengthening this list.
 * What this list is for meanwhile is not failing a correct stack. Measured: adding `reader` to
 * the scan alone reddens the row on a stack nobody has touched, with `No test names the
 * statement "ListBundles"` and the same for `ReadBundles`.
 *
 * The document is not unexamined in the meantime. `scripts/check-stack.mjs` feeds the rendered
 * JSON to `aws accessanalyzer validate-policy`, which is a credentialled row and therefore not
 * this one.
 */
const TEST_ASSERTED_DOCUMENTS = ['bundles', 'publisher_trust', 'publisher'];

/**
 * Paths that must never be tracked under `infra/`, and what each one leaks.
 *
 * The predicates below are deliberately wider than the `infra/` globs in `.gitignore`, and
 * that width is the row. The ignore file covers the spellings an operator will really have at
 * `infra/` top level, `infra/*.tfvars`, `infra/*.tfstate` and the rest, because that is where
 * terraform writes them; a detector that mirrored those globs exactly would catch nothing the
 * ignore file had already missed, which is the whole of what it would be for. So each rule
 * here matches by shape anywhere under `infra/`. Measured with `git check-ignore -v`, four of
 * the shapes are unignored today: `infra/sub/z.tfvars`, `infra/tests/x.tfstate`,
 * `infra/tests/y.tfplan` and `infra/tests/.terraform/x.bin` each matches a rule below and none
 * of them matches a glob there.
 *
 * The top-level spellings the globs do cover still need a rule, because being ignored is not
 * being untracked: a `git add -f`, a rule deleted from the ignore file, or a file created
 * before the rule was written all produce a tracked file in a public repository with no
 * warning anywhere.
 */
const FORBIDDEN_TRACKED = [
	{
		id: 'tfvars',
		matches: (path) => path.endsWith('.tfvars') || path.endsWith('.tfvars.json'),
		what: 'a variable definitions file, which carries the account id, the bucket name and the publisher map',
	},
	{
		id: 'tfstate',
		matches: (path) => path.includes('.tfstate'),
		what: 'Terraform state, which carries every rendered policy and every output',
	},
	{
		id: 'tfplan',
		matches: (path) => path.endsWith('.tfplan'),
		what: 'a saved plan, which carries the same values state does',
	},
	{
		id: 'terraform-dir',
		matches: (path) => path.split('/').includes('.terraform'),
		what: 'the provider cache, which is hundreds of megabytes of vendored binary',
	},
];

/**
 * Where terraform might be. `HEXDOCS_TERRAFORM` wins, so a developer with one outside PATH
 * can point at it rather than being told three rows were skipped, and so this guard's own
 * missing-binary branches are reachable from a test. `check-paint.mjs` takes `HEXDOCS_CHROME`
 * for both of the same reasons.
 */
export function findTerraform() {
	const named = process.env.HEXDOCS_TERRAFORM;
	if (named !== undefined && named !== '') return existsSync(named) ? named : undefined;
	for (const dir of (process.env.PATH ?? '').split(delimiter)) {
		if (dir === '') continue;
		const candidate = join(dir, 'terraform');
		try {
			const stats = statSync(candidate);
			// The executable bit matters rather than mere existence. A directory or a stray
			// text file named `terraform` earlier on PATH would otherwise be reported as the
			// binary, and the three rows would fail with a spawn error instead of skipping.
			if (stats.isFile() && (stats.mode & 0o111) !== 0) return candidate;
		} catch {
			continue;
		}
	}
	return undefined;
}

/**
 * @param {string} binary
 * @param {string} root
 * @param {string[]} args
 */
function terraform(binary, root, args) {
	return spawnSync(binary, args, {
		cwd: root,
		encoding: 'utf8',
		env: {
			...process.env,
			NO_COLOR: '1',
			// The version check that would otherwise be this script's only network call.
			CHECKPOINT_DISABLE: '1',
			// Suppresses the "next steps" advice terraform prints for a human at a terminal,
			// which is noise in a report and shifts the summary line this parses.
			TF_IN_AUTOMATION: '1',
		},
		// `terraform test` prints a line per run block and a plan on failure, and the default
		// 1 MB is reachable on a stack with a few more publishers in its fixtures.
		maxBuffer: 32 * 1024 * 1024,
	});
}

/**
 * Comments removed, line count preserved.
 *
 * Every scan below runs over this rather than over the raw source, and one scan is why:
 * `publishers.tf` carries a comment stating in words that no `...IfExists` operator appears
 * in it, and the trust policy scan looks for exactly that spelling. Over raw text the file
 * documenting the rule is the file reported as breaking it. Measured, that comment is the
 * only line under `infra/` that needs this: with the stripping replaced by the identity
 * function, it is the single new problem in the whole report.
 *
 * The lifecycle scan is not a reason, though `bucket.tf`'s three paragraphs about there being
 * no expiration rule look like one. `DESTRUCTIVE_LIFECYCLE` anchors to a line opening with the
 * block or argument name, or with `dynamic "` and then the name, and no `#` or `//` comment
 * can do either, so that scan reads identically from raw or stripped source. It is not immune
 * to comments in general: a block comment can open a line with the name, and block comments
 * are not stripped either, for the reason below.
 *
 * Whole-line comments only, and the limitation is deliberate rather than unfinished. HCL
 * block comments cannot be stripped without knowing where strings begin and end: `infra/`
 * composes object ARNs as `"${local.bucket_arn}/*"`, so a stripper looking for `/*` would
 * eat the rest of the file from the middle of a string. Nothing under `infra/` uses a block
 * comment or a trailing comment today. If one arrives, the cost is a scan that reads a
 * comment as code and fails naming the line, which is the direction a guard should fail in.
 *
 * Lines are blanked rather than dropped so that a reported line number still matches the
 * file somebody opens.
 *
 * @param {string} text
 */
function stripComments(text) {
	return text
		.split('\n')
		.map((line) => (/^[ \t]*(#|\/\/)/.test(line) ? '' : line))
		.join('\n');
}

/** @param {string} path */
function posix(path) {
	return path.split(sep).join('/');
}

/**
 * Whether a repository-relative path is a file `terraform fmt` would format.
 *
 * One predicate, used for both the disk walk and the git listing, so the two sides of the
 * cross-check below cannot disagree about what counts. A dot segment anywhere in the path is
 * out, matching fmt's own treatment of hidden files and keeping `.terraform/` off both sides.
 *
 * @param {string} path
 */
function isFormatTarget(path) {
	const segments = posix(path).split('/');
	if (segments[0] !== INFRA) return false;
	if (segments.slice(1).some((segment) => segment.startsWith('.'))) return false;
	return FMT_EXTENSIONS.some((extension) => path.endsWith(extension));
}

/**
 * Whether a repository-relative path is configuration written in terraform's JSON syntax.
 *
 * Not a format target, and deliberately not added to `FMT_EXTENSIONS`: `terraform fmt` does
 * not format JSON, so counting one in the fmt row would put a file in that number fmt was
 * never going to read. It is a refusal instead, in the invariants row, because terraform loads
 * a `.tf.json` as native configuration and every scan in that row reads HCL.
 *
 * `.tftest.json` is native too and is deliberately not here: `terraformTest` compares the run
 * blocks that passed against the run blocks it counted off the disk, and one written in JSON
 * fails that pair in both directions already.
 *
 * @param {string} path
 */
function isNativeJson(path) {
	const segments = posix(path).split('/');
	if (segments[0] !== INFRA) return false;
	if (segments.slice(1).some((segment) => segment.startsWith('.'))) return false;
	return path.endsWith('.tf.json');
}

/**
 * Every file under `infra/` the predicate accepts, repository-relative.
 *
 * @param {string} root
 * @param {(path: string) => boolean} [accept] Defaults to the formattable files.
 * @returns {string[]}
 */
function walkInfra(root, accept = isFormatTarget) {
	/** @type {string[]} */
	const found = [];
	/** @type {string[]} */
	const queue = [join(root, INFRA)];

	while (queue.length > 0) {
		const current = /** @type {string} */ (queue.pop());
		/** @type {import('node:fs').Dirent[]} */
		let entries;
		try {
			entries = readdirSync(current, { withFileTypes: true });
		} catch {
			continue;
		}
		for (const entry of entries) {
			if (entry.isSymbolicLink()) continue;
			if (entry.name.startsWith('.')) continue;
			const full = join(current, entry.name);
			if (entry.isDirectory()) {
				queue.push(full);
				continue;
			}
			const where = posix(relative(root, full));
			if (accept(where)) found.push(where);
		}
	}

	return found.sort();
}

/**
 * What git tracks under `infra/`, and what it deliberately ignores there. `null` if git
 * could not answer at all.
 *
 * `git ls-files` rather than a status read, so an operator's scratch file never fails a row.
 * `-z` because a path with a space or a quote in it is otherwise returned quoted, and a
 * quoted path compares unequal to the same path off the disk.
 *
 * The ignored list is the half that would otherwise produce a wrong red row. `infra/*.tfvars`
 * is gitignored on purpose, so an operator who has applied this stack has a real
 * `local.auto.tfvars` on disk carrying the account id and the bucket name. `terraform fmt`
 * reads it, so it is a file this guard counts, and it is exactly not a file CI is missing.
 *
 * @param {string} root
 * @returns {{ tracked: string[], ignored: string[] } | null}
 */
function gitInfraFiles(root) {
	/** @param {string[]} args */
	const list = (args) => {
		const spawned = spawnSync('git', ['ls-files', '-z', ...args, '--', INFRA], {
			cwd: root,
			encoding: 'utf8',
			maxBuffer: 32 * 1024 * 1024,
		});
		if (spawned.error !== undefined || spawned.status !== 0) return null;
		return spawned.stdout.split('\0').filter((name) => name !== '');
	};
	const tracked = list([]);
	if (tracked === null) return null;
	// `--others --ignored` needs `--exclude-standard` or git refuses the combination outright,
	// which would read here as git being unavailable rather than as a wrong invocation.
	const ignored = list(['--others', '--ignored', '--exclude-standard']) ?? [];
	return { tracked, ignored };
}

/**
 * Any top-level block opener, whatever its type and however many labels it carries.
 *
 * It bounds the body scan below, and it has to be type-agnostic rather than the same pattern
 * the caller asked for: `bucket-policy.tf` is a `data` block then a `resource` block and
 * `publishers.tf` is `locals`, `data`, `data`, `resource`, `resource`, so a bound scoped to
 * one type runs straight past a mis-closed block of another and swallows everything to the
 * next block of its own kind.
 *
 * No `g` flag. `test` on a global pattern carries `lastIndex` between calls, so every second
 * line would be searched from the wrong offset.
 */
const ANY_TOP_LEVEL_OPENER = /^[a-z_]+(?:\s+"[^"]*")*\s*\{\s*$/;

/**
 * Top-level blocks of one type, with their labels and their bodies.
 *
 * A parser rather than a scan, because the assertions below are about what is inside one
 * block: `prevent_destroy = true` somewhere in a file says nothing about which resource
 * carries it, and a `description` line proves nothing about which variable it belongs to.
 *
 * It leans on two properties of `terraform fmt` output: a top-level block opens at column 0
 * and closes with a `}` at column 0. That is the row below this one, so a stack this cannot
 * parse is a stack that already has a red row.
 *
 * What it must not do is run past the end of a block, and getting that wrong is silent in both
 * directions at once. A body scan bounded only by the closing brace does not stop where the
 * block does: an indented brace makes it run on to the next block's closing brace, and a brace
 * missing altogether makes it run to the end of the file. Either way the block then passes its
 * own assertions on a later block's `description`, and every block inside the span it swallowed
 * is skipped, so their assertions are never evaluated and the row's count simply gets smaller.
 * A smaller count is not a failing count. Terraform accepts an indented closing brace, so only
 * `terraform fmt` notices, and on a machine with no binary that row is SKIPPED and this one is
 * the only one running.
 *
 * So the scan is bounded by the next top-level opener as well, and the block is kept with the
 * truncated body it did get rather than dropped: the mis-closed block still gets its own
 * assertions, and `closed` is what the caller reports. Keeping both means the row names two
 * problems rather than trading one for another.
 *
 * @param {string} text  Comment-stripped source.
 * @param {string} type  `variable`, `output`, `resource` or `data`.
 * @returns {{ labels: string[], body: string, line: number, closed: boolean }[]}
 */
function topLevelBlocks(text, type) {
	/** @type {{ labels: string[], body: string, line: number, closed: boolean }[]} */
	const blocks = [];
	const lines = text.split('\n');
	const opener = new RegExp(`^${type}\\s+((?:"[^"]*"\\s*)+)\\{\\s*$`);

	for (let index = 0; index < lines.length; index += 1) {
		const match = opener.exec(/** @type {string} */ (lines[index]));
		if (match === null) continue;
		const labels = [.../** @type {string} */ (match[1]).matchAll(/"([^"]*)"/g)].map(
			(found) => /** @type {string} */ (found[1]),
		);
		let end = index + 1;
		while (
			end < lines.length &&
			lines[end] !== '}' &&
			!ANY_TOP_LEVEL_OPENER.test(/** @type {string} */ (lines[end]))
		) {
			end += 1;
		}
		const closed = end < lines.length && lines[end] === '}';
		blocks.push({
			labels,
			body: lines.slice(index + 1, end).join('\n'),
			line: index + 1,
			closed,
		});
		// One before the opener that stopped the scan, so the loop's own increment lands on it
		// and the block below a mis-closed one is parsed rather than swallowed with it.
		index = closed ? end : end - 1;
	}

	return blocks;
}

/**
 * The invariants row: everything answerable from the files, with no binary.
 *
 * Each entry in the returned problem list is one failed assertion, and `count` is how many
 * were evaluated rather than how many files were read. That distinction is the point of the
 * row: reading nine files and asserting nothing about them is the failure mode, and a file
 * count would hide it behind a healthy looking number.
 *
 * @param {string} root
 * @returns {InvariantsResult}
 */
function stackInvariants(root) {
	/** @type {string[]} */
	const problems = [];
	/** @type {Set<string>} */
	const arms = new Set();
	let count = 0;
	/**
	 * One assertion, tagged with the arm of this row it belongs to.
	 *
	 * `count` is how many assertions were evaluated and `arms` is which of them, and the two
	 * answer different questions. A count says the row did work; only the arm list says which
	 * work, and a floor on the count is satisfied by whatever subset of these assertions
	 * happens to run often enough. Measured before this list existed: the row reported 74
	 * assertions and the suite held it to more than 20, so fifty-odd evaluations could have
	 * stopped happening with every row green. `test/infra.test.ts` claims every id emitted
	 * here, in both directions,
	 * which is `kit/test/compile/rules-fire.test.ts`'s shape applied to a guard rather than to
	 * a lint rule pack.
	 *
	 * An id repeated across iterations of a loop is one arm and not several. What the claims
	 * table is about is whether an assertion still runs at all; how many times it ran is the
	 * count beside it.
	 *
	 * @param {string} arm     A short stable id. Renaming one is a change to the claims table.
	 * @param {boolean} ok
	 * @param {string} problem
	 */
	const assert = (arm, ok, problem) => {
		count += 1;
		arms.add(arm);
		if (!ok) problems.push(problem);
	};

	// Configuration and test files, and deliberately not `.tfvars`.
	//
	// A tfvars assigns values to declared variables and can declare no block at all, so it can
	// carry none of the constructs asserted below. What it can carry is the account id and the
	// bucket name: `infra/*.tfvars` is gitignored precisely because an operator who has applied
	// this stack has a real one here. Nothing is gained by reading it and the one thing that
	// could go wrong is a message quoting a line out of it.
	const paths = walkInfra(root).filter(
		(where) => where.endsWith('.tf') || where.endsWith('.tftest.hcl'),
	);
	if (paths.length === 0) {
		// No arms, and that is not a hole in the claims table: the table is checked against a
		// run over this repository, where every arm is reached. A row that returned early with
		// arms it never evaluated would be claiming coverage it did not have, which is the
		// thing the list exists to refuse.
		return {
			...check('stack invariants', 0, 'assertions', [
				`${INFRA}/ holds no .tf file. Either the stack was moved and this guard was not, or the walk stopped matching, and either way nothing here is checked.`,
			]),
			arms: [],
		};
	}

	/** @type {{ where: string, code: string }[]} */
	const files = [];
	for (const where of paths) {
		try {
			files.push({ where, code: stripComments(readFileSync(join(root, where), 'utf8')) });
		} catch (error) {
			problems.push(
				`${where} could not be read: ${error instanceof Error ? error.message : String(error)}`,
			);
		}
	}
	const configuration = files.filter((file) => file.where.endsWith('.tf'));
	const allCode = configuration.map((file) => file.code).join('\n');

	// ---- no configuration written in terraform's JSON syntax ---------------
	//
	// A refusal rather than a second parser, because every scan in this row reads HCL and none
	// of them can be taught JSON cheaply. Terraform loads a `.tf.json` as native configuration,
	// so an expiration rule, a second `aws_s3_bucket` with no `prevent_destroy`, an undescribed
	// variable or a `StringEqualsIfExists` written in one is configuration this row cannot see,
	// and the validate row's resource count is short by whatever it declares. Measured before
	// this assertion existed: a planted `infra/planted.tf.json` carrying a lifecycle expiration
	// gave four PASS rows while terraform planned a resource nothing here had counted.
	const nativeJson = walkInfra(root, isNativeJson);
	assert(
		'native-json',
		nativeJson.length === 0,
		`${nativeJson.join(', ')} is terraform configuration in JSON syntax. Every scan in this row reads HCL and terraform reads both, so anything declared there is configuration no assertion here can see and no count here includes. Write it as HCL.`,
	);

	// ---- no lifecycle action that deletes anything -------------------------
	for (const file of files) {
		DESTRUCTIVE_LIFECYCLE.lastIndex = 0;
		/** @type {string[]} */
		const hits = [];
		for (const found of file.code.matchAll(DESTRUCTIVE_LIFECYCLE)) {
			const line = file.code.slice(0, found.index).split('\n').length;
			hits.push(`${file.where}:${line} declares ${String(found[1])}`);
		}
		assert(
			'no-destructive-lifecycle',
			hits.length === 0,
			`${hits.join(', ')}. S3 Lifecycle is the one mechanism that ignores the bucket policy entirely, so an expiration or transition rule is a delete that DenyObjectDeletion cannot see, in a store whose whole value is that a labelled sha resolves to the same bytes forever.`,
		);
	}

	// ---- every variable and every output is described ----------------------
	const variables = configuration.flatMap((file) =>
		topLevelBlocks(file.code, 'variable').map((block) => ({ file: file.where, ...block })),
	);
	const outputs = configuration.flatMap((file) =>
		topLevelBlocks(file.code, 'output').map((block) => ({ file: file.where, ...block })),
	);

	// Both parses are asserted to have found something before their contents are asserted.
	// Without this a parser that stopped matching reports zero variables, zero failures and a
	// green row, which is the same silent pass the file-count rule exists to refuse.
	assert(
		'variables-parsed',
		variables.length > 0,
		`No variable block was parsed out of ${INFRA}/. The parse expects a top-level block opening at column 0 and closing with a brace at column 0, which is terraform fmt output, so a red fmt row below explains this one.`,
	);
	assert(
		'outputs-parsed',
		outputs.length > 0,
		`No output block was parsed out of ${INFRA}/. Same parse and same cause as the variables above.`,
	);

	for (const block of [...variables, ...outputs]) {
		const described = /^[ \t]+description\s*=\s*(?!""\s*$)\S/m.test(block.body);
		assert(
			'described',
			described,
			`${block.file}:${block.line} declares "${String(block.labels[0])}" with no description, or with an empty one. An operator writes this stack's values into an untracked tfvars from README.md and reads them back out of terraform output; a field with no description is one they have to read the HCL to fill in.`,
		);
	}

	// ---- the two resources that must survive a terraform destroy -----------
	const resources = configuration.flatMap((file) =>
		topLevelBlocks(file.code, 'resource').map((block) => ({ file: file.where, ...block })),
	);
	for (const [type, why] of [
		[
			'aws_s3_bucket',
			'Destroying the bucket is the one operation that ends the guarantee a labelled sha resolves to the same bytes forever, and unlike everything else in this stack it cannot be undone by putting a policy back.',
		],
		[
			'aws_iam_openid_connect_provider',
			'Every publisher role trusts this provider by ARN. Replacing it breaks every publish in the account at once and cannot be undone by putting the roles back, because their trust policies would name a destroyed ARN.',
		],
	]) {
		const matching = resources.filter((resource) => resource.labels[0] === type);
		assert(
			'protected-resource-count',
			matching.length === 1,
			`Expected exactly one ${String(type)} resource under ${INFRA}/ and found ${matching.length}. The prevent_destroy assertion below has nothing to attach to.`,
		);
		for (const resource of matching) {
			assert(
				'prevent-destroy',
				/^[ \t]+prevent_destroy\s*=\s*true\s*$/m.test(resource.body),
				`${resource.file}:${resource.line}, ${String(type)}."${String(resource.labels[1])}" carries no lifecycle prevent_destroy. ${String(why)}`,
			);
		}
	}

	const dataBlocks = configuration.flatMap((file) =>
		topLevelBlocks(file.code, 'data').map((block) => ({ file: file.where, ...block })),
	);

	// ---- every block the parser opened was closed --------------------------
	//
	// One assertion over all four parses. A mis-closed block is not a formatting nicety here:
	// the body scan stops at the next top-level opener, so the block gets a truncated body and
	// everything the missing brace would have swallowed is still parsed and still asserted
	// about. What nothing else would say is that the parse itself was wrong, and the number of
	// assertions on its own cannot say it, because a parse that reads less asserts less.
	const unclosed = [...variables, ...outputs, ...resources, ...dataBlocks].filter(
		(block) => !block.closed,
	);
	assert(
		'blocks-closed',
		unclosed.length === 0,
		`${unclosed
			.map(
				(block) =>
					`${block.file}:${block.line} opens ${block.labels.map((label) => `"${label}"`).join(' ')} and no closing brace at column 0 follows it`,
			)
			.join(
				', ',
			)}. The parse reads terraform fmt output, where a top-level block closes with a brace at column 0, so an indented or missing one leaves this row reading a body that is not the block's.`,
	);

	// ---- the policy documents say the statements they are meant to ---------
	const documents = dataBlocks.filter((block) => block.labels[0] === 'aws_iam_policy_document');

	// Both directions over the table, which is what a one-directional loop over it cannot do.
	// A document with no entry was uncovered in silence: nothing reads its statements, nothing
	// says so, and the row is green. `scripts/lint.mjs` cross-checks `REQUIRED_DIRS` against the
	// directories on disk for exactly this reason.
	for (const document of documents) {
		const name = String(document.labels[1]);
		assert(
			'document-in-table',
			Object.hasOwn(POLICY_DOCUMENT_SIDS, name),
			`${document.file} declares aws_iam_policy_document."${name}" and this guard's table of expected statements does not name it, so nothing here reads what it says. Add it to POLICY_DOCUMENT_SIDS, and to TEST_ASSERTED_DOCUMENTS if the policy tests assert against it.`,
		);
	}
	for (const name of TEST_ASSERTED_DOCUMENTS) {
		assert(
			'test-asserted-in-table',
			Object.hasOwn(POLICY_DOCUMENT_SIDS, name),
			`TEST_ASSERTED_DOCUMENTS names "${name}" and POLICY_DOCUMENT_SIDS has no entry for it, so the every-statement-is-claimed-by-a-test scan below reads no statement for that document at all.`,
		);
	}

	for (const [name, expected] of Object.entries(POLICY_DOCUMENT_SIDS)) {
		const document = documents.find((entry) => entry.labels[1] === name);
		// Asserted every time round rather than from inside the absent branch. An
		// `assert(false, ...)` reached only when the document is missing is an arm that never
		// evaluates on a healthy stack: it appears in no run's arm list, so the claims table in
		// `test/infra.test.ts` cannot hold it in both directions and it could be deleted with
		// every row green. Evaluating it always costs three assertions and makes the arm visible.
		assert(
			'document-declared',
			document !== undefined,
			`No aws_iam_policy_document named "${name}" is declared under ${INFRA}/, so nothing here reads the statements this guard expects of it.`,
		);
		if (document === undefined) continue;
		const sids = [...document.body.matchAll(/^[ \t]+sid\s*=\s*"([^"]*)"/gm)].map(
			(found) => found[1],
		);
		assert(
			'document-sids',
			JSON.stringify(sids) === JSON.stringify(expected),
			`${document.file}, aws_iam_policy_document."${name}" declares [${sids.join(', ')}] and should declare [${expected.join(', ')}], in that order. A statement deleted from one of these documents leaves no plan diff, no warning and no error; the only thing that notices is somebody deleting a published bundle.`,
		);
	}

	// ---- every statement is claimed by the policy tests --------------------
	//
	// Both directions, and what each one catches is worth stating exactly, because the two
	// sentences that used to be here claimed the other thing.
	//
	// Forwards: a statement the policy documents declare and no test file mentions anywhere.
	// That is a statement nothing asserts about, and every statement in these policies is a
	// deny or a scoping condition whose absence renders as a policy that reads correct and
	// applies cleanly. Backwards: a statement a test names and no document declares, which is
	// an assertion about something that no longer exists and passes forever. This is
	// `REQUIRED_VARIANTS` in `fixtures/nodes.ts` applied to policy statements.
	//
	// What it does NOT catch, measured, is the deletion of a `run` block whose Sids another
	// block also names. The scan is `includes` over the whole comment-stripped test text, so it
	// asks whether the name appears anywhere, not which block names it or whether anything is
	// asserted about it. The first run block in `policies.tftest.hcl` lists every bucket Sid as
	// a literal inside its own assertion, so it covers for each block carrying the substantive
	// assertions about those statements and they cover for it. Measured against the seven-block
	// file this was written for: five of the seven could each be deleted with all four rows
	// green, and only the trust policy block and the publisher block, whose Sids appear nowhere
	// else, went red here. The `terraform test` row cannot see a deletion either, for the reason
	// written at its own header, so a run block deleted from the middle of that file is caught
	// by nothing in this repository.
	const testSources = files.filter((file) => file.where.endsWith('.tftest.hcl'));
	assert(
		'test-sources-exist',
		testSources.length > 0,
		`No .tftest.hcl file was found under ${INFRA}/, so nothing asserts what any policy statement says.`,
	);
	if (testSources.length > 0) {
		const testText = testSources.map((file) => file.code).join('\n');
		const declared = Object.values(POLICY_DOCUMENT_SIDS).flat();
		const expectations = /** @type {Record<string, string[]>} */ (POLICY_DOCUMENT_SIDS);
		const asserted = TEST_ASSERTED_DOCUMENTS.flatMap((name) => expectations[name] ?? []);
		for (const sid of asserted) {
			assert(
				'sid-claimed-by-test',
				testText.includes(`"${sid}"`),
				`No test names the statement "${sid}". Every statement in these policies is a deny or a scoping condition whose absence renders as a policy that reads correct and applies cleanly, so one nothing asserts about is one nothing would notice losing.`,
			);
		}
		// `GitHub[A-Za-z]+` is its own alternative rather than a case of the third one. The
		// trust policy's Sid begins with the word, and `[A-Z][A-Za-z]*(?:Own|GitHub)` needs a
		// character before it, so the one statement in the stack that grants rather than denies
		// was the one the reverse scan could not see.
		const named = [
			...testText.matchAll(
				/"(Deny[A-Za-z]+|GitHub[A-Za-z]+|[A-Z][A-Za-z]*(?:Own|GitHub)[A-Za-z]*)"/g,
			),
		].map((found) => found[1]);
		for (const sid of [...new Set(named)]) {
			assert(
				'sid-declared',
				declared.includes(sid),
				`A test names the statement "${sid}" and no statement of that name is expected of any policy document in this guard's table, which is cross-checked against the aws_iam_policy_document blocks under ${INFRA}/ in both directions above. An assertion about a statement that does not exist passes forever.`,
			);
		}
	}

	// ---- no ...IfExists operator in any trust policy condition -------------
	const publishers = files.find((file) => file.where === `${INFRA}/publishers.tf`);
	assert(
		'publishers-present',
		publishers !== undefined,
		`${INFRA}/publishers.tf is missing, so nothing scanned the trust policy conditions.`,
	);
	if (publishers !== undefined) {
		const hits = [...publishers.code.matchAll(/[A-Za-z]*IfExists/g)].map(
			(found) => `${publishers.where}:${publishers.code.slice(0, found.index).split('\n').length}`,
		);
		assert(
			'no-if-exists',
			hits.length === 0,
			`${hits.join(', ')} uses an ...IfExists condition operator. Absence evaluates true under those operators, so one misspelled OIDC claim name grants instead of denying, and nothing catches it: aws accessanalyzer validate-policy does not check claim names in a provider-prefixed namespace at all.`,
		);
	}

	// ---- the publish workflow and the trust policy agree about the branch --
	//
	// What is compared is two literals in two tracked files: the single push branch in the
	// workflow template, and the default declared for the publisher branch in `variables.tf`.
	// A one-sided edit of either fails here, which is worth having because the two are edited
	// months apart and a token minted for a branch the trust policy does not pin is refused by
	// STS with a message naming neither branch nor file.
	//
	// What it cannot see is a per-publisher override, and that is not a small gap. The trust
	// policy interpolates `var.publishers[key].branch`, whose value lives in an untracked
	// tfvars this row deliberately does not read, and the stack's own test file exercises
	// exactly that shape with a publisher on `release`. A repository publishing from another
	// branch also has a hand-edited workflow, because the template's branch is a literal, and
	// nothing here can read another repository's committed workflow file. So this pair of
	// literals is the whole of what is checkable offline, and `scripts/check-stack.mjs` is
	// where the applied ref per publisher can be read back.
	//
	// Both sides are read rather than compared against a literal "main". A guard that hard
	// coded the value on both sides would pass whatever the two files said.
	let workflowBranches = /** @type {string[]} */ ([]);
	try {
		const template = readFileSync(join(root, WORKFLOW_TEMPLATE), 'utf8');
		workflowBranches = [...template.matchAll(/branches:\s*\[\s*([^\]\s]+)\s*\]/g)].map(
			(found) => /** @type {string} */ (found[1]),
		);
	} catch (error) {
		problems.push(
			`${WORKFLOW_TEMPLATE} could not be read: ${error instanceof Error ? error.message : String(error)}`,
		);
	}
	const trustBranches = [
		...allCode.matchAll(/\bbranch\s*=\s*optional\(\s*string\s*,\s*"([^"]*)"\s*\)/g),
	].map((found) => /** @type {string} */ (found[1]));

	assert(
		'workflow-one-branch',
		new Set(workflowBranches).size === 1,
		`${WORKFLOW_TEMPLATE} names ${workflowBranches.length} push branches (${workflowBranches.join(', ') || 'none'}). One is what the trust policy can be compared against; a template that triggers on two needs the publisher map to carry both.`,
	);
	assert(
		'trust-one-branch',
		new Set(trustBranches).size === 1,
		`${INFRA}/variables.tf declares ${trustBranches.length} defaults for the publisher branch (${trustBranches.join(', ') || 'none'}). The trust policy pins refs/heads/<branch>, so there has to be exactly one default to compare.`,
	);
	assert(
		'branches-agree',
		workflowBranches.length > 0 &&
			trustBranches.length > 0 &&
			workflowBranches[0] === trustBranches[0],
		`${WORKFLOW_TEMPLATE} triggers on "${String(workflowBranches[0])}" and ${INFRA}/variables.tf defaults the publisher branch to "${String(trustBranches[0])}". A push to the branch the workflow watches would mint a token whose ref claim the trust policy refuses, and STS reports that as an access denial naming neither branch nor file.`,
	);

	// ---- nothing that leaks the estate is tracked under infra/ -------------
	const git = gitInfraFiles(root);
	if (git === null) {
		// A problem rather than a quiet omission. Four assertions below depend on git being
		// able to answer, and a report that dropped them would be four assertions lighter with
		// nothing saying so.
		problems.push(
			'`git ls-files -- infra` failed, so nothing checked whether a tfvars, a state file or the provider cache is tracked in a public repository.',
		);
	} else {
		for (const rule of FORBIDDEN_TRACKED) {
			const hits = git.tracked.filter((path) => rule.matches(posix(path)));
			assert(
				'not-tracked',
				hits.length === 0,
				`git tracks ${hits.join(', ')}, which is ${rule.what}. This repository is public and the infrastructure it provisions is not. It may have arrived through an ordinary git add: these predicates are wider than the .gitignore globs on purpose, so not every shape they match is ignored. Untrack it, and if the commit has been pushed treat the values in it as exposed.`,
			);
		}
	}

	return {
		...check('stack invariants', count, 'assertions', problems, {
			note: `${configuration.length} .tf files, ${variables.length} variables, ${outputs.length} outputs, ${resources.length} resources`,
		}),
		arms: [...arms].sort(),
	};
}

/**
 * The formatting row, and the cross-check that keeps its count honest.
 *
 * `terraform fmt -check` prints the files that need formatting and nothing else, so its own
 * output cannot say how many it read. The count comes off the disk, and the disk walk is
 * then compared against what git tracks in both directions, because a walk that stopped
 * matching reports a smaller number and smaller is not failing.
 *
 * @param {string} binary
 * @param {string} root
 * @param {string} version
 */
function terraformFmt(binary, root, version) {
	/** @type {string[]} */
	const problems = [];
	const onDisk = walkInfra(root);

	const spawned = terraform(binary, root, ['fmt', '-check', '-recursive', '-no-color', INFRA]);
	if (spawned.error !== undefined) {
		problems.push(`Could not run ${binary}: ${spawned.error.message}`);
	} else if (spawned.status === 3) {
		// 3, and only 3. `terraform fmt -check` reserves 3 for "these files would change" and
		// uses another status for a real error: measured on 1.14.7, an unparseable `.tf` exits
		// 2. So a guard treating any non-zero status as a formatting problem would report a
		// parse failure as a formatting failure and send somebody to run fmt over a file fmt
		// cannot read.
		for (const name of (spawned.stdout ?? '').split('\n').filter((line) => line.trim() !== '')) {
			problems.push(
				`${name.trim()} is not terraform fmt clean. Run \`terraform -chdir=${INFRA} fmt -recursive\`.`,
			);
		}
	} else if (spawned.status !== 0) {
		problems.push(
			`\`terraform fmt -check -recursive ${INFRA}\` exited ${spawned.status}, which is an error rather than a formatting difference: ${(spawned.stderr ?? '').trim().split('\n').slice(-6).join(' ')}`,
		);
	}

	const git = gitInfraFiles(root);
	const trackedTargets = (git?.tracked ?? []).map(posix).filter(isFormatTarget).sort();
	let note = `${version}, ${onDisk.length} on disk`;

	if (git === null) {
		problems.push(
			'`git ls-files -- infra` failed, so the disk walk was compared against nothing and a file it missed would only have made this number smaller.',
		);
	} else {
		const walked = new Set(onDisk);
		for (const name of trackedTargets) {
			if (walked.has(name)) continue;
			problems.push(
				`git tracks ${name} and the walk did not find it, so terraform fmt examined a file this row did not count. The walk skips symlinks and dot segments; one of those now covers a real configuration file.`,
			);
		}

		// The other direction, and it is bounded twice rather than absolute.
		//
		// A file on disk that git neither tracks nor ignores is a stack CI plans differently
		// from the one on the laptop, which is worth failing on. An ignored one is the opposite:
		// `infra/*.tfvars` is gitignored on purpose, so an operator who has applied this stack
		// has a real `local.auto.tfvars` here that terraform fmt reads and CI must never see.
		//
		// The second bound is that when git tracks nothing at all under infra/ the whole stack
		// is simply not committed yet, which `git status` says far more loudly than this row
		// could and which no per-file message improves. The note carries the number compared, so
		// a run where this direction had nothing to say does not read as one where it passed.
		const local = new Set((git.ignored ?? []).map(posix));
		if (trackedTargets.length > 0) {
			const isTracked = new Set(trackedTargets);
			for (const name of onDisk) {
				if (isTracked.has(name) || local.has(name)) continue;
				problems.push(
					`${name} is on disk and git neither tracks nor ignores it. CI checks out what git tracks, so terraform validates one stack here and a different one there.`,
				);
			}
		}
		const ignoredTargets = onDisk.filter((name) => local.has(name));
		note += `, ${trackedTargets.length} tracked by git`;
		if (ignoredTargets.length > 0) note += `, ${ignoredTargets.length} gitignored and local`;
		if (trackedTargets.length === 0) {
			note +=
				' (the stack is not committed yet, so only the tracked-but-not-walked direction had anything to compare)';
		}
	}

	return check('terraform fmt', onDisk.length, 'files', problems, { note });
}

/**
 * The validate row.
 *
 * Warnings count as failures. The stack can produce exactly one, the deprecated lifecycle
 * `filter` spelling on a 6.x provider, and that warning is about the block this stack most
 * needs to keep saying what it says. A row that passed with a warning would let the one
 * diagnostic worth reading scroll past.
 *
 * @param {string} binary
 * @param {string} root
 * @param {string} version
 */
function terraformValidate(binary, root, version) {
	/** @type {string[]} */
	const problems = [];

	// Measured from the source rather than from the command, because a passing validate names
	// no file. `resource` blocks rather than planned instances: two of these are for_each over
	// var.publishers, so the number of resources in an account depends on a tfvars this
	// repository does not have.
	const resources = walkInfra(root)
		.filter((where) => where.endsWith('.tf'))
		.flatMap((where) =>
			topLevelBlocks(stripComments(readFileSync(join(root, where), 'utf8')), 'resource'),
		);

	const spawned = terraform(binary, root, [`-chdir=${INFRA}`, 'validate', '-no-color', '-json']);
	if (spawned.error !== undefined) {
		problems.push(`Could not run ${binary}: ${spawned.error.message}`);
		return check('terraform validate', resources.length, 'resources', problems, { note: version });
	}

	/** @type {{ valid?: boolean, error_count?: number, warning_count?: number, diagnostics?: any[] }} */
	let report = {};
	try {
		report = JSON.parse(spawned.stdout ?? '');
	} catch {
		problems.push(
			`\`terraform validate -json\` exited ${spawned.status} and its stdout is not JSON: ${(spawned.stderr || spawned.stdout || '').trim().split('\n').slice(-6).join(' ')}`,
		);
		return check('terraform validate', resources.length, 'resources', problems, { note: version });
	}

	if (report.valid !== true) problems.push('terraform validate reports the configuration invalid.');
	if ((report.warning_count ?? 0) !== 0) {
		problems.push(
			`terraform validate reports ${report.warning_count} warnings. A clean stack has none: the one this configuration can produce is the deprecated lifecycle filter spelling, which is about the block that keeps the store from being emptied.`,
		);
	}
	for (const diagnostic of report.diagnostics ?? []) {
		const where =
			diagnostic?.range?.filename === undefined
				? ''
				: `${diagnostic.range.filename}:${diagnostic.range.start?.line ?? '?'} `;
		problems.push(
			`${where}${diagnostic?.severity ?? 'diagnostic'}: ${diagnostic?.summary ?? ''} ${diagnostic?.detail ?? ''}`.trim(),
		);
	}

	return check('terraform validate', resources.length, 'resources', problems, { note: version });
}

/**
 * The policy test row.
 *
 * The number of run blocks that passed is compared against the number declared on disk. Both
 * numbers are needed, because `terraform test` reports only what it ran: a test file that
 * stopped being collected, by moving into a subdirectory terraform does not read, reports zero
 * passed and zero failed and exits 0, which reads as a clean run.
 *
 * What this pair does NOT catch is a deleted `run` block, and saying otherwise would be worse
 * than saying nothing. Both numbers come off the same file, so a deletion lowers them together
 * and they still match.
 *
 * The invariants row does not close that either, and the same rule applies to saying so. Its
 * Sid cross-check asks whether each declared statement is named anywhere in the test text, in
 * both directions, which catches a statement no test ever mentioned and a test naming a
 * statement no document declares. It does not ask which run block names a Sid or whether
 * anything is asserted about it, so deleting a run block whose Sids another block also names
 * changes nothing there. Measured against the seven-block `policies.tftest.hcl` this was
 * written for: five of the seven could each be deleted with all four rows green, because the
 * first block lists every bucket Sid as a literal inside its own assertion.
 *
 * @param {string} binary
 * @param {string} root
 * @param {string} version
 */
function terraformTest(binary, root, version) {
	/** @type {string[]} */
	const problems = [];

	const testFiles = walkInfra(root).filter((where) => where.endsWith('.tftest.hcl'));
	const declared = testFiles.reduce((total, where) => {
		const code = stripComments(readFileSync(join(root, where), 'utf8'));
		return total + [...code.matchAll(/^run\s+"[^"]*"\s*\{/gm)].length;
	}, 0);

	const spawned = terraform(binary, root, [`-chdir=${INFRA}`, 'test', '-no-color']);
	const output = `${spawned.stdout ?? ''}${spawned.stderr ?? ''}`;

	if (spawned.error !== undefined) {
		problems.push(`Could not run ${binary}: ${spawned.error.message}`);
		return check('terraform test', 0, 'run blocks', problems, { note: version });
	}

	const summary = /(\d+) passed, (\d+) failed/.exec(output);
	if (summary === null) {
		problems.push(
			`\`terraform test\` exited ${spawned.status} and printed no "N passed, N failed" summary: ${output.trim().split('\n').slice(-12).join(' | ')}`,
		);
		return check('terraform test', 0, 'run blocks', problems, { note: version });
	}

	const passed = Number(summary[1]);
	const failed = Number(summary[2]);

	if (failed > 0) {
		problems.push(
			`${failed} of ${passed + failed} run blocks failed. Each one asserts a statement whose absence is invisible: there is no plan diff and no error for a deny that stopped being written.`,
		);
		for (const line of output.trim().split('\n').slice(-20)) problems.push(line);
	}

	if (passed !== declared) {
		problems.push(
			`${passed} run blocks passed and ${declared} are declared across ${testFiles.join(', ') || 'no test file'}. A deleted run block lowers the count above rather than failing it, which is why this number comes off the disk.`,
		);
	}

	return check('terraform test', passed, 'run blocks', problems, {
		note: `${version}, ${declared} declared in ${testFiles.length} test files`,
	});
}

/**
 * @param {string} [root] The tree to check. Parameterised so this guard's own failure paths
 *   are reachable from a test against a doctored copy, exactly as `check-cli.mjs` and
 *   `lint.mjs` are. A guard whose red output nobody has seen is a guard nobody has tested.
 * @returns {import('./lib/report.mjs').CheckResult[]}
 */
export function run(root = ROOT) {
	const invariants = stackInvariants(root);

	const binary = findTerraform();
	if (binary === undefined) {
		const reason =
			'No terraform on PATH. Set HEXDOCS_TERRAFORM to one, or install it: the stack still has to be formatted, valid and tested before it is applied.';
		if (process.env.CI === 'true') {
			// SKIPPED is a deliberate, explained non-run. In CI it is not deliberate: the
			// workflow installs terraform with hashicorp/setup-terraform, so a missing binary
			// there means the environment changed under the check rather than that somebody
			// chose to skip it. `check-paint.mjs` draws the same line for the same reason.
			const broken = [
				`${reason} CI installs it with hashicorp/setup-terraform, so this is a broken environment rather than a skip.`,
			];
			return [
				invariants,
				check('terraform fmt', 0, 'files', broken),
				check('terraform validate', 0, 'resources', broken),
				check('terraform test', 0, 'run blocks', broken),
			];
		}
		return [
			invariants,
			skipped('terraform fmt', 'files', reason),
			skipped('terraform validate', 'resources', reason),
			skipped('terraform test', 'run blocks', reason),
		];
	}

	// One extra spawn, and it buys the report the only fact that explains a difference between
	// two machines running the same rows. `required_version` is `>= 1.14.0`, terraform enforces
	// that itself at validate, so this is for the reader rather than for a check.
	const versioned = terraform(binary, root, ['version', '-no-color']);
	const version = (versioned.stdout ?? '').split('\n')[0]?.trim() || binary;

	const initialised = existsSync(join(root, INFRA, '.terraform'));
	if (!initialised) {
		// NOT RUN rather than a failure of the configuration, and rather than a skip. The
		// configuration might be perfect; nothing here knows, because validate and test both
		// refuse without a provider. NOT RUN fails the run, which is right: an uninitialised
		// checkout is a state somebody has to fix before the stack is checked at all.
		const reason = `${INFRA}/.terraform is absent. Run \`terraform -chdir=${INFRA} init -backend=false\`, which is the only step here that touches the network.`;
		return [
			invariants,
			terraformFmt(binary, root, version),
			notRun('terraform validate', 'resources', reason),
			notRun('terraform test', 'run blocks', reason),
		];
	}

	return [
		invariants,
		terraformFmt(binary, root, version),
		terraformValidate(binary, root, version),
		terraformTest(binary, root, version),
	];
}

/**
 * Only when invoked directly, and resolved through symlinks on both sides.
 *
 * The text comparison the older guards use, `import.meta.url === pathToFileURL(argv[1]).href`,
 * is false through any symlink: argv carries the path the shell was given and `import.meta.url`
 * carries the resolved one. The script then prints nothing and exits 0.
 *
 * In those guards that is latent rather than live, and the difference is worth writing down so
 * the next reader does not go and "fix" a row that is already safe. `package.json` invokes each
 * of them by a relative path that is not a symlink, so the text comparison holds there; and on
 * the day it stopped holding, the child would print nothing, `countExamined` in
 * `scripts/verify.mjs` reads 0 out of an empty string, and `check` turns a zero into a FAIL.
 * No ladder row except `paint` carries `allowZero`, so a silent child is a red row and not a
 * quiet pass.
 *
 * The reason this file needs the resolved form regardless is specific to what it guards. A
 * terraform guard is one somebody runs by absolute path from an infra working directory, which
 * is exactly where a symlinked checkout or a shim in `~/bin` puts one string in argv and
 * another in `import.meta.url`.
 */
function isProgram() {
	const argv = process.argv[1];
	if (argv === undefined) return false;
	try {
		return realpathSync(argv) === realpathSync(fileURLToPath(import.meta.url));
	} catch {
		return false;
	}
}

if (isProgram()) {
	const { ok } = render('hex-docs terraform stack', run());
	process.exit(ok ? 0 : 1);
}
