/**
 * One consumer edit, and the one idea the whole install turns on.
 *
 * `present` is the same function the matching `wiring-*` check calls. It is shared by
 * being named once in `PRESENT` below and referenced from both places, and
 * `kit/test/wiring/install.test.ts` asserts the reference identity rather than the
 * behaviour. That identity is what makes "already installed" and "correctly installed"
 * one fact: `install` re-running is a no-op precisely when `verify-install` passes, and
 * there is no third state where one is satisfied and the other is not. Idempotency is
 * therefore not a property anyone maintains; it is the same function answering the same
 * question twice.
 *
 * `apply` returns `null` when its anchor is missing or is not unique. That is the honest
 * version of "abort only the edits whose own write target was hand-edited": there is no
 * managed-region convention anywhere in hex-web to detect against. An exhaustive grep
 * for `BEGIN MANAGED`, `@generated` and `AUTOGENERATED` across every `.ts .tsx .json
 * .yaml .mjs .css .sh` returns four whole-file "Code generated by the Encore client
 * generator. DO NOT EDIT." headers and nothing else, and zero of the files edited here
 * are generated: `routes.ts` is ninety-five lines of which about half is prose comment,
 * and `root.tsx`'s CSP doc comment alone is fifty-five lines. So "hand-edited" is not
 * knowable, and "I cannot find exactly one place to put this" is.
 *
 * `present` reads the file's text and the descriptor's path arithmetic, with one exception
 * that is the point of the step that introduced it. `PRESENT.routes` reads the consumer's
 * route table through its own `react-router routes --json`, because the table `routes.ts`
 * produces is not in its text: step 5's token test passed over a table the site's own loader
 * refused. Assertions about the filesystem, such as whether a `paths` target resolves to a
 * real file or whether a declared submodule is actually committed, live in `checks.ts`.
 * Without that split, applying an edit could leave `present` false through no fault of the
 * applier, and `install` would report a refusal on a write that worked.
 */

import type { CheckId } from '../../../src/contracts/lint.js';
import { docsRouteRows } from '../../../src/site/address.js';
import type { Exec } from '../exec/run.js';

import { parseGitmodules, parseWorkspacePackages, workspaceMatches } from './detect.js';
import { rootInstruction, routesInstruction, sitemapInstruction } from './instructions.js';
import {
	derives,
	detectIndent,
	entryIndent,
	exportsDefault,
	exportsHeaders,
	insertIntoBlock,
	parseJsonc,
	soleBlock,
	soleBlockIn,
	stripComments,
	valueImportSpecifiers,
} from './needles.js';
import { ALWAYS_RUN, prebuildFragment, readPrebuild, splitScript } from './prebuild.js';
import { readRouteTable, routeTableProblems } from './route-table.js';
import {
	DOCS_REMOTE,
	DOCS_ROUTE_MODULE,
	DOCS_SERVER_MODULE,
	dirnamePosix,
	joinPosix,
	resolveFrom,
	validConfigs,
	type DocsRouteKind,
	type SiteDescriptor,
} from './site.js';
import {
	GITIGNORE_ENTRIES,
	checkDocsShim,
	docsMachineRouteModule,
	docsPageRouteModule,
	docsServerModule,
	mcpServerEntry,
} from './templates.js';

/** What a predicate or an applier may use beyond the text and the descriptor. */
export interface EditContext {
	/** The recipe runner. One predicate uses it: the route table's. */
	readonly exec: Exec;
	/** `install --bucket`. Written into a prebuild fragment `install` creates, and nowhere else. */
	readonly bucket?: string | undefined;
}

export interface Edit {
	/** Stable, kebab case. It is what `install`'s output names and what a test looks up. */
	readonly id: string;
	/** The `wiring-*` row this edit satisfies. Several edits may share one. */
	readonly check: CheckId;
	/** Repository-relative. A directory for the one edit whose subject is not a file. */
	readonly file: string;
	present(text: string | null, site: SiteDescriptor, ctx: EditContext): boolean;
	/** `null` refuses. Never called when `present` is already true. */
	apply(text: string | null, site: SiteDescriptor, ctx: EditContext): string | null;
	/** Printed when `apply` refuses, and always for a `byHand` edit. */
	readonly instruction: string;
	/**
	 * Printed, never written. Six of the seventeen edits, each for its own reason.
	 *
	 * Three are insertions into hand-authored files whose surrounding prose is the consuming
	 * repository's actual documentation: the route table, `root.tsx` and the sitemap. One is
	 * a git operation that has to create a gitlink as well as a stanza. One is a compiler
	 * option that lives in a shared configuration this install does not own. One is the
	 * site config, which needs a project id, a mount path and a labelled commit that nothing
	 * here knows.
	 */
	readonly byHand?: true;
}

// ---------------------------------------------------------------------------
// The shared predicates
// ---------------------------------------------------------------------------

/** The three `paths` entries a consuming site needs, and what each must resolve to. */
export function tsconfigPathEntries(site: SiteDescriptor): [string, string][] {
	return [
		['@hex-pro/docs', `${site.mountFromSite}/src/index.ts`],
		['@hex-pro/docs/render', `${site.mountFromSite}/src/render/index.ts`],
		['@hex-pro/docs/contracts', `${site.mountFromSite}/src/contracts/index.ts`],
	];
}

/**
 * `react` and `react/*`, mapped to the site's own `@types/react`.
 *
 * `tsc` resolves a bare import from a file under the submodule by walking up from that file,
 * and neither consumer has a `node_modules/react` above its mount: hex-web's is under
 * `apps/front`, and kcalc's root has none. Measured, ten TS2307 and TS2875 errors from
 * `src/render` without the mapping and none with it. The target is the types package and
 * never `node_modules/react`, which Vite follows too and which then bundles a second React
 * into the server build.
 *
 * Its own edit rather than two more rows of `tsconfig-paths`, because that applier refuses
 * the whole edit when any missing key is already present, so a consumer that had mapped
 * `react` by another spelling got no `@hex-pro/docs` entries at all.
 */
export const REACT_TYPES_ENTRIES: readonly (readonly [string, string])[] = [
	['react', './node_modules/@types/react'],
	['react/*', './node_modules/@types/react/*'],
];

function paths(text: string | null): Record<string, unknown> | null {
	if (text === null) return null;
	const parsed = parseJsonc(text);
	if (parsed === null || typeof parsed !== 'object') return null;
	const compilerOptions = (parsed as { compilerOptions?: unknown }).compilerOptions;
	if (compilerOptions === null || typeof compilerOptions !== 'object') return null;
	const table = (compilerOptions as { paths?: unknown }).paths;
	if (table === null || typeof table !== 'object') return null;
	return table as Record<string, unknown>;
}

function firstTarget(table: Record<string, unknown>, key: string): string | null {
	const value = table[key];
	if (!Array.isArray(value)) return null;
	const first = value[0];
	return typeof first === 'string' ? first : null;
}

/**
 * The directory a `paths` target names, so two spellings of one directory compare equal.
 *
 * `./node_modules/@types/react`, `node_modules/@types/react` and
 * `node_modules/@types/react/index.d.ts` are one resolution, and a consumer that wrote any of
 * them has wired it. Resolved from the site directory, which is where both consumers' own
 * `baseUrl` of `.` puts it; a `baseUrl` elsewhere would move every target together and is not
 * a shape either consumer has.
 */
function targetDirectory(site: SiteDescriptor, target: string): string {
	return resolveFrom(site.site, target.replace(/\/index\.d\.ts$/, ''));
}

/**
 * `compilerOptions.resolveJsonModule`, following `extends`.
 *
 * Following it is not optional, and this is the fact that would otherwise have made the
 * check fail both correctly configured consumers forever. Neither `apps/front` nor
 * `kcalc-web/front` sets `resolveJsonModule` in its own `tsconfig.json`; both extend
 * `config/tsconfig.front.json`, which sets it to `true`. hex-web's base config also
 * carries a `//` comment, so the extended file has to go through `stripComments` as well.
 *
 * The chain is followed for a bounded number of hops and only for a single string
 * `extends`. An array `extends` is TypeScript 5.0 and neither consumer uses one; where it
 * appears this returns `null`, which the check reports as "could not determine" rather
 * than as a failure.
 */
export function resolveJsonModuleOf(site: SiteDescriptor, file: string, depth = 0): boolean | null {
	if (depth > 8) return null;
	const text = site.files.read(file);
	if (text === null) return null;
	const parsed = parseJsonc(text);
	if (parsed === null || typeof parsed !== 'object') return null;
	const compilerOptions = (parsed as { compilerOptions?: unknown }).compilerOptions;
	if (compilerOptions !== null && typeof compilerOptions === 'object') {
		const value = (compilerOptions as { resolveJsonModule?: unknown }).resolveJsonModule;
		if (typeof value === 'boolean') return value;
	}
	const extend = (parsed as { extends?: unknown }).extends;
	if (typeof extend !== 'string') return null;
	return resolveJsonModuleOf(site, resolveFrom(dirnamePosix(file), extend), depth + 1);
}

function scripts(text: string | null): Record<string, unknown> | null {
	if (text === null) return null;
	const parsed = parseJsonc(text);
	if (parsed === null || typeof parsed !== 'object') return null;
	const table = (parsed as { scripts?: unknown }).scripts;
	if (table === null || typeof table !== 'object') return null;
	return table as Record<string, unknown>;
}

/**
 * What the server module is missing, as sentences that follow its file name.
 *
 * The relative-import arm is the defect this module exists to close, and it is not a style
 * rule. `routes.ts` imports this file and React Router evaluates `routes.ts` with no Vite
 * plugins, so an alias that works everywhere else in the site does not resolve here.
 * Measured on both consumers as "Cannot find package '@hex-pro/docs'", which the step-5
 * predicate passed because it only asked for three calls.
 */
export function docsServerProblems(text: string): string[] {
	const problems: string[] = [];
	for (const needle of ['docsServer(', 'docsRouteRows(']) {
		if (!derives(text, needle)) problems.push(`does not call \`${needle}\`.`);
	}
	const stripped = stripComments(text);
	for (const name of ['DOCS_ROUTES', 'DOCS']) {
		if (!new RegExp(`export\\s+const\\s+${name}\\b`).test(stripped)) {
			problems.push(`does not export \`${name}\`.`);
		}
	}
	for (const specifier of valueImportSpecifiers(text)) {
		if (specifier.startsWith('.')) continue;
		problems.push(
			`imports \`${specifier}\` for its value, which React Router's route config loader cannot resolve: it runs with no Vite plugins, so only a relative path reaches the package.`,
		);
	}
	return problems;
}

/**
 * What a docs route module is missing, as sentences that follow its file name.
 *
 * The same predicate for `install`, which writes the template only when the file is absent,
 * and for the check, which reads whatever is there. A stub that exists and reads nothing is
 * therefore refused by both rather than being unchanged to one and red in the other.
 */
export function routeModuleProblems(kind: DocsRouteKind, text: string): string[] {
	const problems: string[] = [];
	if (kind === 'page') {
		if (!derives(text, 'DOCS.page(')) problems.push('does not call `DOCS.page(`.');
		const stripped = stripComments(text);
		if (!/export\s+const\s+handle\b/.test(stripped) || !/\bDOCS_HANDLE\b/.test(stripped)) {
			problems.push(
				'does not export `DOCS_HANDLE` as its `handle`, so root.tsx cannot tell a docs page from any other address and ships every one noindex.',
			);
		}
		if (!exportsDefault(text)) {
			problems.push('has no default export, so every docs page is served as a resource route.');
		}
	} else {
		if (!derives(text, 'DOCS.resource(')) problems.push('does not call `DOCS.resource(`.');
		if (exportsDefault(text)) {
			problems.push(
				'has a default export, so every machine address renders the site shell around plain text.',
			);
		}
	}
	if (exportsHeaders(text)) problems.push('exports `headers`.');
	return problems;
}

/** What `root.tsx` is missing, as sentences that follow its file name. */
export function rootSeoProblems(text: string): string[] {
	const problems: string[] = [];
	if (!derives(text, 'docsSeoFromMatches(')) {
		problems.push('does not call `docsSeoFromMatches(`, so every docs page ships noindex.');
		return problems;
	}
	const stripped = stripComments(text);
	if (!/\.indexable\b/.test(stripped)) {
		problems.push('does not read the docs answer `indexable`, so a fallback page is not noindex.');
	}
	if (!/\.languages\b/.test(stripped)) {
		problems.push(
			"does not read the docs answer `languages`, so a docs page's alternates still name every language.",
		);
	}
	return problems;
}

/** What the sitemap is missing, as sentences that follow its file name. */
export function sitemapProblems(text: string): string[] {
	const problems: string[] = [];
	const stripped = stripComments(text);
	if (!derives(text, 'DOCS.sitemap()')) problems.push('does not call `DOCS.sitemap()`.');
	const imported = [...stripped.matchAll(/import\s*\{([^}]*)\}\s*from\s*["']([^"']+)["']/g)].some(
		(match) => /\bDOCS\b/.test(match[1] ?? '') && /(^|\/)lib\/docs\.server$/.test(match[2] ?? ''),
	);
	if (!imported) problems.push('does not import `DOCS` from `lib/docs.server`.');
	if (!/\.languages\b/.test(stripped)) {
		problems.push(
			"never reads an entry's `languages`, so every docs page is listed in every language, fallback translations included.",
		);
	}
	return problems;
}

const routePageModule = (text: string | null): boolean =>
	text !== null && routeModuleProblems('page', text).length === 0;

const routeMachineModule = (text: string | null): boolean =>
	text !== null && routeModuleProblems('machine', text).length === 0;

export const PRESENT = {
	submodule(text: string | null, site: SiteDescriptor): boolean {
		return parseGitmodules(text ?? '').some((stanza) => stanza.path === site.mount);
	},

	/**
	 * Not enrolled, and any exclusion written the way the existing guard matches it.
	 *
	 * The question is enrolment, not the presence of a line. On hex-web the answer is
	 * "enrolled" until an exclusion is added, because line 3 is `- common/*`. On kcalc
	 * the answer is already "not enrolled": the file is an explicit literal include list
	 * with no glob and no `!` line anywhere, so an exclusion there would be inert
	 * decoration and a check that demanded one would fail a correctly wired repository
	 * forever.
	 *
	 * The quoting half is not cosmetic. `apps/front/scripts/check-tools.mjs:944` tests
	 * `workspace.includes('"!' + submodule.path + '"')`, a raw substring including the
	 * double quotes, so an unquoted YAML exclusion satisfies pnpm and fails that guard,
	 * which is a red row in a file this install never touched.
	 */
	workspaceExclusion(text: string | null, site: SiteDescriptor): boolean {
		if (text === null) return true;
		const entries = parseWorkspacePackages(text);
		let enrolled = false;
		let excluded = false;
		for (const entry of entries) {
			if (!workspaceMatches(entry, site.mount)) continue;
			if (entry.startsWith('!')) excluded = true;
			else enrolled = true;
		}
		if (excluded) return text.includes(`"!${site.mount}"`);
		return !enrolled;
	},

	tsconfigPaths(text: string | null, site: SiteDescriptor): boolean {
		const table = paths(text);
		if (table === null) return false;
		return tsconfigPathEntries(site).every(([key, target]) => firstTarget(table, key) === target);
	},

	tsconfigReactTypes(text: string | null, site: SiteDescriptor): boolean {
		const table = paths(text);
		if (table === null) return false;
		return REACT_TYPES_ENTRIES.every(([key, target]) => {
			const actual = firstTarget(table, key);
			return actual !== null && targetDirectory(site, actual) === targetDirectory(site, target);
		});
	},

	tsconfigResolveJson(_text: string | null, site: SiteDescriptor): boolean {
		return resolveJsonModuleOf(site, joinPosix(site.site, 'tsconfig.json')) === true;
	},

	deployHashDirs(text: string | null, site: SiteDescriptor): boolean {
		// No deploy configuration at all means this repository does not deploy through
		// hex-terraform, so there is no hash to extend and nothing to do. The check
		// reports that state as a skip; here it is simply satisfied.
		if (text === null) return true;
		const parsed = parseJsonc(text);
		if (parsed === null || typeof parsed !== 'object') return false;
		if (site.projectType === null) return false;
		const hash = (parsed as { hash?: unknown }).hash;
		if (hash === null || typeof hash !== 'object') return false;
		const extra = (hash as { extra_dirs?: unknown }).extra_dirs;
		if (extra === null || typeof extra !== 'object') return false;
		const list = (extra as Record<string, unknown>)[site.projectType];
		return Array.isArray(list) && list.includes(site.mount);
	},

	/** The build chain runs a prefetch the CLI accepts, then the guard. `readPrebuild` says how. */
	prebuildHook(text: string | null, site: SiteDescriptor): boolean {
		const table = scripts(text);
		return table !== null && readPrebuild(table, site).problems.length === 0;
	},

	/**
	 * The shim exists and spawns `verify-install` for this site.
	 *
	 * Not byte equality, and the reason is that byte equality would make this row fail on
	 * every consumer the moment the submodule is bumped to a kit whose generator produced
	 * one different character, which fails `prebuild`, which fails the deploy. A shim that
	 * an older kit wrote still works, because it holds no copy of what is checked: it
	 * spawns the CLI and renders whatever rows come back.
	 *
	 * The cost is stated rather than hidden: `install` will not refresh an existing shim,
	 * so a change to the generator reaches a consumer only when somebody deletes the file
	 * and runs `hexdocs install --write` again. That is the trade for not turning a
	 * submodule bump into a broken build.
	 */
	checkDocsShim(text: string | null, site: SiteDescriptor): boolean {
		if (text === null) return false;
		return text.includes('"verify-install"') && text.includes(JSON.stringify(site.site));
	},

	gitignore(text: string | null): boolean {
		if (text === null) return false;
		const lines = text.split('\n').map((line) => line.trim());
		return GITIGNORE_ENTRIES.every((entry) => lines.includes(entry));
	},

	siteConfig(_text: string | null, site: SiteDescriptor): boolean {
		return site.projects.length > 0;
	},

	/**
	 * `app/lib/docs.server.ts` builds the server and the rows, and imports the package by a
	 * path the route config loader can resolve.
	 *
	 * Not byte equality: the header says "safe to edit", because a consumer with two
	 * documented projects and a reason to order them differently has somewhere to do it. So
	 * the predicate asks what the rest of the wiring depends on and nothing else.
	 */
	docsServer(text: string | null): boolean {
		return text !== null && docsServerProblems(text).length === 0;
	},

	pageRouteModule: routePageModule,

	machineRouteModule: routeMachineModule,

	/**
	 * The site's own loader accepts its route config, and every docs row is where it belongs.
	 *
	 * False when there are no docs rows to look for, which is every first install: `install`
	 * runs before `hexdocs scaffold site` writes a config, and a valid config always yields
	 * machine rows. Over zero rows `routeTableProblems` has nothing to report, so this used to
	 * answer true, `install` called the routes edit unchanged, never printed the insertions,
	 * and its by-hand row listed the remaining edits as the whole of what was left.
	 */
	routes(_text: string | null, site: SiteDescriptor, ctx: EditContext): boolean {
		const rows = docsRouteRows(validConfigs(site));
		if (rows.length === 0) return false;
		const table = readRouteTable(site, ctx.exec);
		return table.kind === 'loaded' && routeTableProblems(table.routes, rows).length === 0;
	},

	rootSeo(text: string | null): boolean {
		return text !== null && rootSeoProblems(text).length === 0;
	},

	sitemap(text: string | null): boolean {
		return text !== null && sitemapProblems(text).length === 0;
	},

	mcpJson(text: string | null, site: SiteDescriptor): boolean {
		if (text === null) return false;
		const parsed = parseJsonc(text);
		if (parsed === null || typeof parsed !== 'object') return false;
		const servers = (parsed as { mcpServers?: unknown }).mcpServers;
		if (servers === null || typeof servers !== 'object') return false;
		const entry = (servers as Record<string, unknown>)['hexdocs'];
		if (entry === null || typeof entry !== 'object') return false;
		return (entry as { command?: unknown }).command === mcpServerEntry(site).command;
	},
} as const;

// ---------------------------------------------------------------------------
// The appliers
// ---------------------------------------------------------------------------

function withTrailingNewline(text: string): string {
	return text.endsWith('\n') ? text : `${text}\n`;
}

/** The bounds of the `packages:` list, as line indices into the split text. */
function packagesBlock(lines: readonly string[]): { from: number; to: number } | null {
	const from = lines.findIndex((line) => /^packages\s*:/.test(line));
	if (from === -1) return null;
	let to = lines.length;
	for (let i = from + 1; i < lines.length; i += 1) {
		const line = lines[i] as string;
		if (line.trim() === '') continue;
		if (/^\s/.test(line)) continue;
		if (line.trimStart().startsWith('#')) continue;
		to = i;
		break;
	}
	return { from, to };
}

/**
 * Inserts the `paths` entries a table does not have yet.
 *
 * A key that is present with a target the predicate does not accept is left alone and the
 * edit refuses. It means somebody pointed the specifier somewhere on purpose, and a silent
 * retarget is the one edit whose failure shows up as a wrong module being compiled rather
 * than as a build error.
 */
function insertPathEntries(
	text: string | null,
	wanted: readonly (readonly [string, string])[],
	satisfied: (table: Record<string, unknown>, key: string, target: string) => boolean,
): string | null {
	if (text === null) return null;
	const block = soleBlock(text, 'paths');
	if (block === null || block.kind !== 'object') return null;
	const table = paths(text);
	if (table === null) return null;
	const missing = wanted.filter(([key, target]) => !satisfied(table, key, target));
	if (missing.length === 0) return text;
	if (missing.some(([key]) => key in table)) return null;
	return insertIntoBlock(
		text,
		block,
		missing.map(([key, target]) => `${JSON.stringify(key)}: [${JSON.stringify(target)}]`),
	);
}

/**
 * Whether an always-run script already names the launcher or the guard, or cannot be read.
 *
 * Refused rather than appended after, which is the step-5 upgrade path this exists for. A
 * prebuild carrying `hexdocs prefetch --root ../..` fails the predicate, and appending the
 * correct fragment behind it leaves the broken one first in the chain, where it still exits 2
 * and stops the build before the correct one runs. The instruction names the segment to
 * replace instead.
 */
function namesTheGuard(table: Record<string, unknown>): boolean {
	return ALWAYS_RUN.some((name) => {
		const value = table[name];
		if (typeof value !== 'string') return false;
		const segments = splitScript(value);
		if (segments === null) return true;
		return segments.some((segment) =>
			segment.tokens.some((token) => /(^|\/)(hexdocs|check-docs\.mjs)$/.test(token)),
		);
	});
}

const APPLY = {
	workspaceExclusion(text: string | null, site: SiteDescriptor): string | null {
		if (text === null) return null;
		const lines = text.split('\n');
		const block = packagesBlock(lines);
		if (block === null) return null;

		const wanted = `"!${site.mount}"`;
		let lastExclusion = -1;
		let enrolling = -1;
		for (let i = block.from + 1; i < block.to; i += 1) {
			const item = /^(\s*-\s*)(.+?)\s*$/.exec(lines[i] as string);
			if (item === null) continue;
			const value = (item[2] ?? '').replace(/^["']|["']$/g, '');
			if (value.startsWith('!')) lastExclusion = i;
			// An exclusion written without the quotes satisfies pnpm and fails
			// `check-tools.mjs`, so it is rewritten in place rather than duplicated.
			if (value === `!${site.mount}`) {
				lines[i] = `${item[1] ?? '  - '}${wanted}`;
				return lines.join('\n');
			}
			if (!value.startsWith('!') && workspaceMatches(value, site.mount)) enrolling = i;
		}

		const anchor = lastExclusion !== -1 ? lastExclusion : enrolling;
		if (anchor === -1) return null;
		const prefix = /^(\s*-\s*)/.exec(lines[anchor] as string)?.[1] ?? '  - ';
		lines.splice(anchor + 1, 0, `${prefix}${wanted}`);
		return lines.join('\n');
	},

	tsconfigPaths(text: string | null, site: SiteDescriptor): string | null {
		return insertPathEntries(
			text,
			tsconfigPathEntries(site),
			(table, key, target) => firstTarget(table, key) === target,
		);
	},

	tsconfigReactTypes(text: string | null, site: SiteDescriptor): string | null {
		return insertPathEntries(text, REACT_TYPES_ENTRIES, (table, key, target) => {
			const actual = firstTarget(table, key);
			return actual !== null && targetDirectory(site, actual) === targetDirectory(site, target);
		});
	},

	deployHashDirs(text: string | null, site: SiteDescriptor): string | null {
		if (text === null || site.projectType === null) return null;
		const extra = soleBlock(text, 'extra_dirs');
		if (extra === null || extra.kind !== 'object') return null;
		const list = soleBlockIn(text, extra, site.projectType);
		if (list !== null && list.kind === 'array') {
			return insertIntoBlock(text, list, [JSON.stringify(site.mount)]);
		}
		// kcalc's `extra_dirs` holds only a `worker` key, so the site's own key has to be
		// created rather than appended to. `?? []` at the reading end cannot tell the two
		// states apart, which is why they are separated here and in the check's message.
		return insertIntoBlock(text, extra, [
			`${JSON.stringify(site.projectType)}: [${JSON.stringify(site.mount)}]`,
		]);
	},

	/**
	 * Appends to this package's own `prebuild`, never to a script it shares.
	 *
	 * All four hex-web fronts declare the identical `"prebuild":
	 * "../../common/copy-assets.sh"`, so editing that shell script would run the docs
	 * guard for three sites that have no docs. The append is inside the string literal in
	 * the original bytes, which is what preserves the tabs and the key order that
	 * `JSON.stringify` would not.
	 */
	prebuildHook(text: string | null, site: SiteDescriptor, ctx: EditContext): string | null {
		if (text === null) return null;
		const table = scripts(text);
		if (table === null || namesTheGuard(table)) return null;
		const block = soleBlock(text, 'scripts');
		if (block === null || block.kind !== 'object') return null;
		const fragment = prebuildFragment(site, ctx.bucket);

		const existing = table['prebuild'];
		const region = text.slice(block.open, block.close + 1);
		const key = /"prebuild"\s*:\s*"/.exec(region);
		if (typeof existing === 'string' && key?.index !== undefined) {
			// A string that already ends in an operator would take the fragment as the
			// operand of something else, `a & && fragment` being a syntax error and `a || `
			// being a masked prefetch.
			if (/(&|\||;)\s*$/.test(existing)) return null;
			const start = block.open + key.index + key[0].length;
			let cursor = start;
			while (cursor < text.length) {
				if (text[cursor] === '\\') {
					cursor += 2;
					continue;
				}
				if (text[cursor] === '"') break;
				cursor += 1;
			}
			if (cursor >= text.length) return null;
			// An empty or blank prebuild is replaced rather than appended to. Appending gave
			// ` && <fragment>`, which the shell refuses as a syntax error, so every build
			// stopped in prebuild on a file `install` reported as written.
			if (existing.trim() === '') return `${text.slice(0, start)}${fragment}${text.slice(cursor)}`;
			return `${text.slice(0, cursor)} && ${fragment}${text.slice(cursor)}`;
		}
		if (existing !== undefined) return null;
		return insertIntoBlock(text, block, [`"prebuild": ${JSON.stringify(fragment)}`]);
	},

	checkDocsShim(_text: string | null, site: SiteDescriptor): string | null {
		return checkDocsShim(site);
	},

	/**
	 * An insertion, not a round trip.
	 *
	 * A parse and re-serialise was tried and rejected on the output: `JSON.stringify`
	 * puts every array element on its own line, so adding one server reformatted all
	 * three of hex-web's, and the diff of a one-commit file that nobody had touched since
	 * March would have been every line in it. The edit belongs to this package; the rest
	 * of the file belongs to whoever wrote it.
	 */
	mcpJson(text: string | null, site: SiteDescriptor): string | null {
		const entry = mcpServerEntry(site);
		if (text === null) {
			const indent = '\t';
			return (
				'{\n' +
				`${indent}"mcpServers": {\n` +
				`${indent}${indent}"hexdocs": {\n` +
				`${indent}${indent}${indent}"command": ${JSON.stringify(entry.command)},\n` +
				`${indent}${indent}${indent}"args": []\n` +
				`${indent}${indent}}\n` +
				`${indent}}\n` +
				'}\n'
			);
		}
		const block = soleBlock(text, 'mcpServers');
		if (block === null || block.kind !== 'object') return null;
		// A `hexdocs` entry that is present with a different command is somebody's own
		// wiring, and a second key of the same name would be a file that parses to
		// whichever one came last.
		if (/"hexdocs"\s*:/.test(text.slice(block.open, block.close + 1))) return null;
		const indent = entryIndent(text, block);
		const unit = detectIndent(text);
		return insertIntoBlock(text, block, [
			`"hexdocs": {\n${indent}${unit}"command": ${JSON.stringify(entry.command)},\n` +
				`${indent}${unit}"args": []\n${indent}}`,
		]);
	},

	gitignore(text: string | null): string | null {
		const existing = text === null ? '' : withTrailingNewline(text);
		const lines = existing.split('\n').map((line) => line.trim());
		const missing = GITIGNORE_ENTRIES.filter((entry) => !lines.includes(entry));
		if (missing.length === 0) return existing;
		const header = '# Written by `hexdocs install`. Prefetched bundles are build output.';
		return `${existing}${existing === '' ? '' : '\n'}${header}\n${missing.join('\n')}\n`;
	},

	// Created, never rewritten. A file that exists and fails its predicate is a file somebody
	// wrote, and each template's own header invites that.
	docsServer(text: string | null, site: SiteDescriptor): string | null {
		return text === null ? docsServerModule(site) : null;
	},

	pageRouteModule(text: string | null): string | null {
		return text === null ? docsPageRouteModule() : null;
	},

	machineRouteModule(text: string | null): string | null {
		return text === null ? docsMachineRouteModule() : null;
	},

	refuse(): string | null {
		return null;
	},
} as const;

// ---------------------------------------------------------------------------
// The table
// ---------------------------------------------------------------------------

/**
 * One table per descriptor and bucket.
 *
 * Memoised because three of the instructions are shaped to what the consumer's own file
 * looks like, so building the table reads files, and `checks.ts` asks for it once per
 * finding it emits. The cache is keyed on the descriptor object rather than on a path, so
 * a second `detectSite` over the same repository builds a fresh table and re-reads: this
 * is a within-one-run memo and never a cache of the filesystem.
 */
const TABLES = new WeakMap<SiteDescriptor, Map<string, Edit[]>>();

/**
 * Every edit, shaped to the repository in hand.
 *
 * Built per descriptor because half of these need a path computed from it and four need
 * an instruction shaped to what the consumer's own file looks like. The predicates and
 * the appliers are the module-level tables above, so every record carries the same
 * function objects whatever the descriptor, which is what the identity assertion depends
 * on.
 */
export function editsFor(site: SiteDescriptor, bucket?: string): Edit[] {
	const forSite = TABLES.get(site) ?? new Map<string, Edit[]>();
	TABLES.set(site, forSite);
	const key = bucket ?? '';
	const cached = forSite.get(key);
	if (cached !== undefined) return cached;
	const built = buildEdits(site, bucket);
	forSite.set(key, built);
	return built;
}

function prebuildInstruction(
	site: SiteDescriptor,
	file: string,
	bucket: string | undefined,
): string {
	const table = scripts(site.files.read(file));
	const reading = table === null ? null : readPrebuild(table, site);
	const named = reading === null ? [] : [...reading.launcherSegments, ...reading.guardSegments];
	const opening =
		named.length === 0
			? `${file}: append to this package's own prebuild:`
			: `${file}: replace ${named.map((segment) => `\`${segment}\``).join(' and ')} in this package's build chain with:`;
	return [
		opening,
		'',
		`  ${prebuildFragment(site, bucket)}`,
		'',
		...(reading === null || reading.problems.length === 0
			? []
			: [
					'What the current chain does wrong:',
					'',
					...reading.problems.map((problem) => `  ${problem}`),
					'',
				]),
		'There is no CI on this repository, so a check that only runs when somebody types it is',
		'not a guard. prebuild is the one thing that always runs: the deploy builds on the host',
		'before the Docker build, and the container install runs with scripts disabled and never',
		"repeats it. Keep the docs segment in this package's own prebuild string, joined by `&&`",
		'to everything after it, and never in a shell script other front packages share.',
		'',
		'The bucket reaches prefetch through `--bucket` in this private package.json, or through',
		'HEXDOCS_BUCKET in the deploy environment. Never through a site config: an eager glob',
		"inlines the whole config object into every page's JavaScript.",
	].join('\n');
}

function moduleInstruction(file: string, what: string, problems: readonly string[]): string {
	return [
		`${file} exists and ${what}, so it was not rewritten: a file that exists is a file somebody wrote.`,
		'',
		...problems.map((problem) => `  It ${problem}`),
		'',
		'Fix those by hand, or delete the file and run `hexdocs install --write` again, which writes',
		'the template.',
	].join('\n');
}

function buildEdits(site: SiteDescriptor, bucket: string | undefined): Edit[] {
	const read = (file: string): string | null => site.files.read(file);
	const routesFile = joinPosix(site.site, 'app/routes.ts');
	const rootFile = joinPosix(site.site, 'app/root.tsx');
	const sitemapFile = joinPosix(site.site, 'app/routes/sitemap[.]xml.tsx');
	const tsconfigFile = joinPosix(site.site, 'tsconfig.json');
	const packageFile = joinPosix(site.site, 'package.json');
	const serverFile = joinPosix(site.site, DOCS_SERVER_MODULE);
	const pageFile = joinPosix(site.site, 'app', DOCS_ROUTE_MODULE.page);
	const machineFile = joinPosix(site.site, 'app', DOCS_ROUTE_MODULE.machine);
	const problemsOf = (file: string, of: (text: string) => string[]): string[] => {
		const text = read(file);
		return text === null ? [] : of(text);
	};

	return [
		{
			id: 'submodule',
			check: 'wiring-submodule',
			file: '.gitmodules',
			present: PRESENT.submodule,
			apply: APPLY.refuse,
			byHand: true,
			// By hand, against the design that had this as a mechanical append. Writing
			// the stanza alone produces a declared submodule with no gitlink, which is a
			// state the check then has to report and which a fresh clone gets nothing
			// from. `git submodule add` writes the stanza, stages the gitlink and creates
			// the checkout in one operation, and it refuses if the path is already in the
			// index, so an append here would also make that command fail.
			instruction: [
				`Add the submodule at ${site.mount}:`,
				'',
				`  git submodule add ${DOCS_REMOTE} ${site.mount}`,
				'',
				'A stanza in .gitmodules is not a committed submodule. The package is consumed',
				'as TypeScript source through a tsconfig paths entry, so there is no install',
				'step that could fail loudly: on a fresh clone the only symptom is a module',
				'resolution error inside the build, naming a path.',
			].join('\n'),
		},
		{
			id: 'workspace-exclusion',
			check: 'wiring-workspace-exclusion',
			file: 'pnpm-workspace.yaml',
			present: PRESENT.workspaceExclusion,
			apply: APPLY.workspaceExclusion,
			instruction: [
				`pnpm-workspace.yaml: add \`  - "!${site.mount}"\`, with the double quotes.`,
				'',
				'A workspace glob enrols the mount as a package, so `pnpm install` inside it',
				'installs this whole monorepo and ignores kit/pnpm-lock.yaml, which is the',
				'lockfile the toolchain is pinned to. The quotes are load-bearing:',
				'apps/front/scripts/check-tools.mjs matches that literal string including them.',
			].join('\n'),
		},
		{
			id: 'tsconfig-paths',
			check: 'wiring-tsconfig-path',
			file: tsconfigFile,
			present: PRESENT.tsconfigPaths,
			apply: APPLY.tsconfigPaths,
			instruction: [
				`${tsconfigFile}: add these to compilerOptions.paths:`,
				'',
				...tsconfigPathEntries(site).map(
					([key, target]) => `  ${JSON.stringify(key)}: [${JSON.stringify(target)}],`,
				),
				'',
				'vite-tsconfig-paths is the only thing turning these into Vite aliases, so',
				'without them tsc and Vite disagree about the same specifier and the failure',
				'arrives as a resolution error inside a submodule during a deploy. Nothing in',
				'the consuming repository builds a dist/, which is why they point at source.',
			].join('\n'),
		},
		{
			id: 'tsconfig-react-types',
			check: 'wiring-tsconfig-path',
			file: tsconfigFile,
			present: PRESENT.tsconfigReactTypes,
			apply: APPLY.tsconfigReactTypes,
			instruction: [
				`${tsconfigFile}: map react to this site's own types in compilerOptions.paths:`,
				'',
				...REACT_TYPES_ENTRIES.map(
					([key, target]) => `  ${JSON.stringify(key)}: [${JSON.stringify(target)}],`,
				),
				'',
				'The package is compiled from the submodule, and tsc resolves a bare `react` from',
				'there by walking up past a directory that has no node_modules/react. Point these at',
				'@types/react and never at node_modules/react, which Vite follows too and which then',
				'bundles a second React into the server build. A key already mapped somewhere else',
				'was left alone: somebody pointed it there on purpose.',
			].join('\n'),
		},
		{
			id: 'tsconfig-resolve-json',
			check: 'wiring-tsconfig-path',
			file: tsconfigFile,
			present: PRESENT.tsconfigResolveJson,
			apply: APPLY.refuse,
			byHand: true,
			// By hand because on both consumers this option is set in a shared
			// `config/tsconfig.front.json` that other packages extend, and an install
			// scoped to one site has no business editing it.
			instruction: [
				'Set `"resolveJsonModule": true` in the TypeScript configuration this site',
				`extends (${tsconfigFile}, or whichever config it extends).`,
				'',
				`${serverFile} globs *.docs.json with import.meta.glob, and both consumers set`,
				'this option in the shared config every front package extends.',
			].join('\n'),
		},
		{
			id: 'deploy-hash-dirs',
			check: 'wiring-deploy-hash-dirs',
			file: 'deploy.config.json',
			present: PRESENT.deployHashDirs,
			apply: APPLY.deployHashDirs,
			instruction: [
				`deploy.config.json: list ${JSON.stringify(site.mount)} in hash.extra_dirs.${site.projectType ?? '<project type>'}.`,
				'',
				'Change detection is hash based over project directories. A submodule that is',
				'not listed leaves the hash identical when the submodule changes, the deploy',
				'reports unchanged, and production keeps serving the old code.',
			].join('\n'),
		},
		{
			id: 'prebuild-hook',
			check: 'wiring-prebuild-hook',
			file: packageFile,
			present: PRESENT.prebuildHook,
			apply: APPLY.prebuildHook,
			instruction: prebuildInstruction(site, packageFile, bucket),
		},
		{
			id: 'check-docs-shim',
			check: 'wiring-prebuild-hook',
			file: joinPosix(site.site, 'scripts/check-docs.mjs'),
			present: PRESENT.checkDocsShim,
			apply: APPLY.checkDocsShim,
			instruction:
				'The generated guard shim. It holds no copy of what is checked, so a shim an older kit wrote still works; delete it and run install again to take a newer one.',
		},
		{
			id: 'gitignore',
			check: 'wiring-prebuild-hook',
			file: joinPosix(site.site, '.gitignore'),
			present: PRESENT.gitignore,
			apply: APPLY.gitignore,
			instruction: [
				`${joinPosix(site.site, '.gitignore')}: ignore what hexdocs prefetch writes:`,
				'',
				...GITIGNORE_ENTRIES.map((entry) => `  ${entry}`),
				'',
				'Both trees are build output fetched from a bundle keyed by commit. Committing',
				'them puts a copy of every page in every language into the site repository and',
				'makes every prefetch a diff.',
			].join('\n'),
		},
		{
			id: 'site-config',
			check: 'wiring-root-seo',
			file: joinPosix(site.site, 'app/docs'),
			present: PRESENT.siteConfig,
			apply: APPLY.refuse,
			byHand: true,
			instruction: [
				`No <project>.docs.json under ${joinPosix(site.site, 'app/docs')}. Scaffold one for the commit this site should serve:`,
				'',
				`  hexdocs scaffold site --site ${site.site} --project <project> --commit <sha> --version <label> --released <YYYY-MM-DD>`,
				'',
				'It names the mount point, the sidebar label in seven languages and the labelled',
				'commits, and it is the build input the routes and the sitemap are derived from.',
				'`hexdocs prefetch` then `hexdocs sync` fill in its pages afterwards.',
			].join('\n'),
		},
		{
			id: 'docs-server',
			check: 'wiring-routes',
			file: serverFile,
			present: PRESENT.docsServer,
			apply: APPLY.docsServer,
			instruction: moduleInstruction(
				serverFile,
				'does not build the docs server and routes the rest of the wiring reads',
				problemsOf(serverFile, docsServerProblems),
			),
		},
		{
			id: 'route-page-module',
			check: 'wiring-routes',
			file: pageFile,
			present: PRESENT.pageRouteModule,
			apply: APPLY.pageRouteModule,
			instruction: moduleInstruction(
				pageFile,
				'does not serve docs pages the way the route table needs',
				problemsOf(pageFile, (text) => routeModuleProblems('page', text)),
			),
		},
		{
			id: 'route-machine-module',
			check: 'wiring-routes',
			file: machineFile,
			present: PRESENT.machineRouteModule,
			apply: APPLY.machineRouteModule,
			instruction: moduleInstruction(
				machineFile,
				'does not serve the machine addresses the way the route table needs',
				problemsOf(machineFile, (text) => routeModuleProblems('machine', text)),
			),
		},
		{
			id: 'routes',
			check: 'wiring-routes',
			file: routesFile,
			present: PRESENT.routes,
			apply: APPLY.refuse,
			byHand: true,
			instruction: routesInstruction(routesFile, read(routesFile)),
		},
		{
			id: 'root-seo',
			check: 'wiring-root-seo',
			file: rootFile,
			present: PRESENT.rootSeo,
			apply: APPLY.refuse,
			byHand: true,
			instruction: rootInstruction(rootFile),
		},
		{
			id: 'sitemap',
			check: 'wiring-sitemap',
			file: sitemapFile,
			present: PRESENT.sitemap,
			apply: APPLY.refuse,
			byHand: true,
			instruction: sitemapInstruction(sitemapFile, read(sitemapFile)),
		},
		{
			id: 'mcp-json',
			check: 'wiring-mcp',
			file: '.mcp.json',
			present: PRESENT.mcpJson,
			apply: APPLY.mcpJson,
			instruction: [
				'.mcp.json: add the hexdocs server.',
				'',
				`  "hexdocs": ${JSON.stringify(mcpServerEntry(site))}`,
				'',
				'Without it an agent in this repository has no way to read a page, check a tree',
				'or reach a skill.',
			].join('\n'),
		},
	];
}

/** The one edit an id names, for a test and for a message. */
export function editById(site: SiteDescriptor, id: string): Edit | undefined {
	return editsFor(site).find((edit) => edit.id === id);
}
