/**
 * One consumer edit, and the one idea the whole install turns on.
 *
 * `present` is the same function the matching `wiring-*` check calls. It is shared by
 * being named once in `PRESENT` below and referenced from both places, and
 * `kit/test/wiring/install.test.ts` asserts the reference identity rather than the
 * behaviour. That identity is what makes "already installed" and "correctly installed"
 * one fact: `install` re-running is a no-op precisely when `verify-install` passes, and
 * there is no third state where one is satisfied and the other is not. Idempotency is
 * therefore not a property anyone maintains; it is the same function answering the same
 * question twice.
 *
 * `apply` returns `null` when its anchor is missing or is not unique. That is the honest
 * version of "abort only the edits whose own write target was hand-edited": there is no
 * managed-region convention anywhere in hex-web to detect against. An exhaustive grep
 * for `BEGIN MANAGED`, `@generated` and `AUTOGENERATED` across every `.ts .tsx .json
 * .yaml .mjs .css .sh` returns four whole-file "Code generated by the Encore client
 * generator. DO NOT EDIT." headers and nothing else, and zero of the files edited here
 * are generated: `routes.ts` is ninety-five lines of which about half is prose comment,
 * and `root.tsx`'s CSP doc comment alone is fifty-five lines. So "hand-edited" is not
 * knowable, and "I cannot find exactly one place to put this" is.
 *
 * `present` reads the file's text and the descriptor's path arithmetic and nothing else.
 * Assertions that need the filesystem or a process, such as whether a `paths` target
 * resolves to a real file or whether a declared submodule is actually committed, live in
 * `checks.ts`. Without that split, applying an edit could leave `present` false through
 * no fault of the applier, and `install` would report a refusal on a write that worked.
 */

import type { CheckId } from '../../../src/contracts/lint.js';

import { parseGitmodules, parseWorkspacePackages, workspaceMatches } from './detect.js';
import {
	derives,
	detectIndent,
	entryIndent,
	insertIntoBlock,
	parseJsonc,
	soleBlock,
	soleBlockIn,
	stripComments,
} from './needles.js';
import { DOCS_REMOTE, dirnamePosix, joinPosix, resolveFrom, type SiteDescriptor } from './site.js';
import {
	GITIGNORE_ENTRIES,
	checkDocsShim,
	docsLibModule,
	mcpServerEntry,
	settingsInstruction,
} from './templates.js';

export interface Edit {
	/** Stable, kebab case. It is what `install`'s output names and what a test looks up. */
	readonly id: string;
	/** The `wiring-*` row this edit satisfies. Several edits may share one. */
	readonly check: CheckId;
	/** Repository-relative. A directory for the one edit whose subject is not a file. */
	readonly file: string;
	present(text: string | null, site: SiteDescriptor): boolean;
	/** `null` refuses. Never called when `present` is already true. */
	apply(text: string | null, site: SiteDescriptor): string | null;
	/** Printed when `apply` refuses, and always for a `byHand` edit. */
	readonly instruction: string;
	/**
	 * Printed, never written. Seven of the fifteen edits, each for its own reason.
	 *
	 * Three are spreads into hand-authored arrays whose surrounding prose is the
	 * consuming repository's actual documentation. One is a git operation that has to
	 * create a gitlink as well as a stanza. One is a settings file whose merge semantics
	 * could not be established. One is a compiler option that lives in a shared
	 * configuration this install does not own. One is the site config, which needs a
	 * project id, a mount path and a label in seven languages that nothing here knows.
	 */
	readonly byHand?: true;
}

// ---------------------------------------------------------------------------
// The shared predicates
// ---------------------------------------------------------------------------

/** The three `paths` entries a consuming site needs, and what each must resolve to. */
export function tsconfigPathEntries(site: SiteDescriptor): [string, string][] {
	return [
		['@hex-pro/docs', `${site.mountFromSite}/src/index.ts`],
		['@hex-pro/docs/render', `${site.mountFromSite}/src/render/index.ts`],
		['@hex-pro/docs/contracts', `${site.mountFromSite}/src/contracts/index.ts`],
	];
}

/** The `prebuild` fragment. One spelling, so the predicate and the applier agree. */
export function prebuildFragment(site: SiteDescriptor): string {
	return (
		`${site.mountFromSite}/kit/bin/hexdocs prefetch --root ${site.repoFromSite} ` +
		`--site ${site.site} && node scripts/check-docs.mjs`
	);
}

function paths(text: string | null): Record<string, unknown> | null {
	if (text === null) return null;
	const parsed = parseJsonc(text);
	if (parsed === null || typeof parsed !== 'object') return null;
	const compilerOptions = (parsed as { compilerOptions?: unknown }).compilerOptions;
	if (compilerOptions === null || typeof compilerOptions !== 'object') return null;
	const table = (compilerOptions as { paths?: unknown }).paths;
	if (table === null || typeof table !== 'object') return null;
	return table as Record<string, unknown>;
}

function firstTarget(table: Record<string, unknown>, key: string): string | null {
	const value = table[key];
	if (!Array.isArray(value)) return null;
	const first = value[0];
	return typeof first === 'string' ? first : null;
}

/**
 * `compilerOptions.resolveJsonModule`, following `extends`.
 *
 * Following it is not optional, and this is the fact that would otherwise have made the
 * check fail both correctly configured consumers forever. Neither `apps/front` nor
 * `kcalc-web/front` sets `resolveJsonModule` in its own `tsconfig.json`; both extend
 * `config/tsconfig.front.json`, which sets it to `true`. hex-web's base config also
 * carries a `//` comment, so the extended file has to go through `stripComments` as well.
 *
 * The chain is followed for a bounded number of hops and only for a single string
 * `extends`. An array `extends` is TypeScript 5.0 and neither consumer uses one; where it
 * appears this returns `null`, which the check reports as "could not determine" rather
 * than as a failure.
 */
export function resolveJsonModuleOf(site: SiteDescriptor, file: string, depth = 0): boolean | null {
	if (depth > 8) return null;
	const text = site.files.read(file);
	if (text === null) return null;
	const parsed = parseJsonc(text);
	if (parsed === null || typeof parsed !== 'object') return null;
	const compilerOptions = (parsed as { compilerOptions?: unknown }).compilerOptions;
	if (compilerOptions !== null && typeof compilerOptions === 'object') {
		const value = (compilerOptions as { resolveJsonModule?: unknown }).resolveJsonModule;
		if (typeof value === 'boolean') return value;
	}
	const extend = (parsed as { extends?: unknown }).extends;
	if (typeof extend !== 'string') return null;
	return resolveJsonModuleOf(site, resolveFrom(dirnamePosix(file), extend), depth + 1);
}

function scripts(text: string | null): Record<string, unknown> | null {
	if (text === null) return null;
	const parsed = parseJsonc(text);
	if (parsed === null || typeof parsed !== 'object') return null;
	const table = (parsed as { scripts?: unknown }).scripts;
	if (table === null || typeof table !== 'object') return null;
	return table as Record<string, unknown>;
}

/**
 * Which scripts always run, and why only these two.
 *
 * npm and pnpm both fire `prebuild` before `build`, measured on npm 11 and pnpm 10, and
 * `hex-terraform/deploy/src/build.ts` runs one of the two on the deploy host before the
 * Docker build. `build` itself is the other always-run script and is kcalc's own idiom,
 * which inlines its pre-step as `node scripts/build-lastmod.mjs && react-router build`.
 * Anything else is a script somebody has to remember to type, which on a repository with
 * no CI is not a guard.
 */
const ALWAYS_RUN = ['prebuild', 'build'] as const;

export const PRESENT = {
	submodule(text: string | null, site: SiteDescriptor): boolean {
		return parseGitmodules(text ?? '').some((stanza) => stanza.path === site.mount);
	},

	/**
	 * Not enrolled, and any exclusion written the way the existing guard matches it.
	 *
	 * The question is enrolment, not the presence of a line. On hex-web the answer is
	 * "enrolled" until an exclusion is added, because line 3 is `- common/*`. On kcalc
	 * the answer is already "not enrolled": the file is an explicit literal include list
	 * with no glob and no `!` line anywhere, so an exclusion there would be inert
	 * decoration and a check that demanded one would fail a correctly wired repository
	 * forever.
	 *
	 * The quoting half is not cosmetic. `apps/front/scripts/check-tools.mjs:944` tests
	 * `workspace.includes('"!' + submodule.path + '"')`, a raw substring including the
	 * double quotes, so an unquoted YAML exclusion satisfies pnpm and fails that guard,
	 * which is a red row in a file this install never touched.
	 */
	workspaceExclusion(text: string | null, site: SiteDescriptor): boolean {
		if (text === null) return true;
		const entries = parseWorkspacePackages(text);
		let enrolled = false;
		let excluded = false;
		for (const entry of entries) {
			if (!workspaceMatches(entry, site.mount)) continue;
			if (entry.startsWith('!')) excluded = true;
			else enrolled = true;
		}
		if (excluded) return text.includes(`"!${site.mount}"`);
		return !enrolled;
	},

	tsconfigPaths(text: string | null, site: SiteDescriptor): boolean {
		const table = paths(text);
		if (table === null) return false;
		return tsconfigPathEntries(site).every(([key, target]) => firstTarget(table, key) === target);
	},

	tsconfigResolveJson(_text: string | null, site: SiteDescriptor): boolean {
		return resolveJsonModuleOf(site, joinPosix(site.site, 'tsconfig.json')) === true;
	},

	deployHashDirs(text: string | null, site: SiteDescriptor): boolean {
		// No deploy configuration at all means this repository does not deploy through
		// hex-terraform, so there is no hash to extend and nothing to do. The check
		// reports that state as a skip; here it is simply satisfied.
		if (text === null) return true;
		const parsed = parseJsonc(text);
		if (parsed === null || typeof parsed !== 'object') return false;
		if (site.projectType === null) return false;
		const hash = (parsed as { hash?: unknown }).hash;
		if (hash === null || typeof hash !== 'object') return false;
		const extra = (hash as { extra_dirs?: unknown }).extra_dirs;
		if (extra === null || typeof extra !== 'object') return false;
		const list = (extra as Record<string, unknown>)[site.projectType];
		return Array.isArray(list) && list.includes(site.mount);
	},

	prebuildHook(text: string | null, site: SiteDescriptor): boolean {
		const table = scripts(text);
		if (table === null) return false;
		return ALWAYS_RUN.some((name) => {
			const value = table[name];
			return (
				typeof value === 'string' &&
				value.includes('hexdocs prefetch') &&
				value.includes(`--site ${site.site}`) &&
				value.includes('check-docs.mjs')
			);
		});
	},

	/**
	 * The shim exists and spawns `verify-install` for this site.
	 *
	 * Not byte equality, and the reason is that byte equality would make this row fail on
	 * every consumer the moment the submodule is bumped to a kit whose generator produced
	 * one different character, which fails `prebuild`, which fails the deploy. A shim that
	 * an older kit wrote still works, because it holds no copy of what is checked: it
	 * spawns the CLI and renders whatever rows come back.
	 *
	 * The cost is stated rather than hidden: `install` will not refresh an existing shim,
	 * so a change to the generator reaches a consumer only when somebody deletes the file
	 * and runs `hexdocs install --write` again. That is the trade for not turning a
	 * submodule bump into a broken build.
	 */
	checkDocsShim(text: string | null, site: SiteDescriptor): boolean {
		if (text === null) return false;
		return text.includes('"verify-install"') && text.includes(JSON.stringify(site.site));
	},

	/**
	 * `app/lib/docs.ts` derives its three exports, however it has been reformatted.
	 *
	 * Not byte equality, unlike the shim, and the difference is deliberate: the header
	 * says "safe to edit" because a consumer with two documented projects and a reason to
	 * order them differently has somewhere to do it. So the predicate asks whether the
	 * module still derives from the three functions, which is what every needle in
	 * `checks.ts` then depends on.
	 */
	docsLib(text: string | null): boolean {
		if (text === null) return false;
		return (
			derives(text, 'docsLocalisedPathsFor(DOCS_SITES)') &&
			derives(text, 'docsRouteRows(DOCS_SITES)') &&
			derives(text, 'docsSitemapRows(DOCS_SITES)')
		);
	},

	siteConfig(_text: string | null, site: SiteDescriptor): boolean {
		return site.projects.length > 0;
	},

	mcpJson(text: string | null, site: SiteDescriptor): boolean {
		if (text === null) return false;
		const parsed = parseJsonc(text);
		if (parsed === null || typeof parsed !== 'object') return false;
		const servers = (parsed as { mcpServers?: unknown }).mcpServers;
		if (servers === null || typeof servers !== 'object') return false;
		const entry = (servers as Record<string, unknown>)['hexdocs'];
		if (entry === null || typeof entry !== 'object') return false;
		return (entry as { command?: unknown }).command === mcpServerEntry(site).command;
	},

	mcpSettings(_text: string | null, site: SiteDescriptor): boolean {
		return settingsSatisfied(site).ok;
	},

	gitignore(text: string | null): boolean {
		if (text === null) return false;
		const lines = text.split('\n').map((line) => line.trim());
		return GITIGNORE_ENTRIES.every((entry) => lines.includes(entry));
	},

	routes(text: string | null): boolean {
		if (text === null) return false;
		return derives(text, 'DOCS_ROUTES');
	},

	localisedPaths(text: string | null): boolean {
		if (text === null) return false;
		return derives(text, 'DOCS_PATHS');
	},

	sitemap(text: string | null): boolean {
		if (text === null) return false;
		return derives(text, 'DOCS_SITEMAP');
	},
} as const;

/**
 * Whether some settings file enables the server and grants the skills directory.
 *
 * Two ways to be enabled, and both are real. hex-web lists its three servers by name in
 * `enabledMcpjsonServers`; kcalc sets `enableAllProjectMcpServers: true` and lists one.
 * A check that only understood the first would fail a correctly wired kcalc forever,
 * which is the same shape of mistake as demanding a workspace exclusion there.
 *
 * Both files are read because neither is authoritative. `.claude/settings.json` does not
 * exist in hex-web at all, and its `.claude/settings.local.json` is ignored by the user's
 * global git ignore rather than by the repository, so it reaches no clone. The row says
 * which file carried the answer for exactly that reason.
 */
export function settingsSatisfied(site: SiteDescriptor): {
	ok: boolean;
	enabledBy: string | null;
	directoryIn: string | null;
	inspected: string[];
} {
	const candidates = ['.claude/settings.json', '.claude/settings.local.json'];
	const skills = `${site.mount}/.claude/skills`;
	let enabledBy: string | null = null;
	let directoryIn: string | null = null;
	const inspected: string[] = [];

	for (const file of candidates) {
		const text = site.files.read(file);
		if (text === null) continue;
		inspected.push(file);
		const parsed = parseJsonc(text);
		if (parsed === null || typeof parsed !== 'object') continue;
		const settings = parsed as Record<string, unknown>;
		const named = settings['enabledMcpjsonServers'];
		const all = settings['enableAllProjectMcpServers'];
		if (all === true || (Array.isArray(named) && named.includes('hexdocs'))) {
			enabledBy ??= file;
		}
		const permissions = settings['permissions'];
		if (permissions !== null && typeof permissions === 'object') {
			const directories = (permissions as { additionalDirectories?: unknown })
				.additionalDirectories;
			if (Array.isArray(directories) && directories.some((entry) => entry === skills)) {
				directoryIn ??= file;
			}
		}
	}

	return { ok: enabledBy !== null && directoryIn !== null, enabledBy, directoryIn, inspected };
}

// ---------------------------------------------------------------------------
// The appliers
// ---------------------------------------------------------------------------

function withTrailingNewline(text: string): string {
	return text.endsWith('\n') ? text : `${text}\n`;
}

/** The bounds of the `packages:` list, as line indices into the split text. */
function packagesBlock(lines: readonly string[]): { from: number; to: number } | null {
	const from = lines.findIndex((line) => /^packages\s*:/.test(line));
	if (from === -1) return null;
	let to = lines.length;
	for (let i = from + 1; i < lines.length; i += 1) {
		const line = lines[i] as string;
		if (line.trim() === '') continue;
		if (/^\s/.test(line)) continue;
		if (line.trimStart().startsWith('#')) continue;
		to = i;
		break;
	}
	return { from, to };
}

const APPLY = {
	workspaceExclusion(text: string | null, site: SiteDescriptor): string | null {
		if (text === null) return null;
		const lines = text.split('\n');
		const block = packagesBlock(lines);
		if (block === null) return null;

		const wanted = `"!${site.mount}"`;
		let lastExclusion = -1;
		let enrolling = -1;
		for (let i = block.from + 1; i < block.to; i += 1) {
			const item = /^(\s*-\s*)(.+?)\s*$/.exec(lines[i] as string);
			if (item === null) continue;
			const value = (item[2] ?? '').replace(/^["']|["']$/g, '');
			if (value.startsWith('!')) lastExclusion = i;
			// An exclusion written without the quotes satisfies pnpm and fails
			// `check-tools.mjs`, so it is rewritten in place rather than duplicated.
			if (value === `!${site.mount}`) {
				lines[i] = `${item[1] ?? '  - '}${wanted}`;
				return lines.join('\n');
			}
			if (!value.startsWith('!') && workspaceMatches(value, site.mount)) enrolling = i;
		}

		const anchor = lastExclusion !== -1 ? lastExclusion : enrolling;
		if (anchor === -1) return null;
		const prefix = /^(\s*-\s*)/.exec(lines[anchor] as string)?.[1] ?? '  - ';
		lines.splice(anchor + 1, 0, `${prefix}${wanted}`);
		return lines.join('\n');
	},

	tsconfigPaths(text: string | null, site: SiteDescriptor): string | null {
		if (text === null) return null;
		const block = soleBlock(text, 'paths');
		if (block === null || block.kind !== 'object') return null;
		const table = paths(text);
		if (table === null) return null;
		const missing = tsconfigPathEntries(site).filter(
			([key, target]) => firstTarget(table, key) !== target,
		);
		if (missing.length === 0) return text;
		// A key that is present with the wrong target is left alone and reported rather
		// than rewritten. It means somebody pointed the specifier somewhere on purpose,
		// and a silent retarget is the one edit whose failure shows up as a wrong module
		// being compiled rather than as a build error.
		if (missing.some(([key]) => key in table)) return null;
		return insertIntoBlock(
			text,
			block,
			missing.map(([key, target]) => `${JSON.stringify(key)}: [${JSON.stringify(target)}]`),
		);
	},

	deployHashDirs(text: string | null, site: SiteDescriptor): string | null {
		if (text === null || site.projectType === null) return null;
		const extra = soleBlock(text, 'extra_dirs');
		if (extra === null || extra.kind !== 'object') return null;
		const list = soleBlockIn(text, extra, site.projectType);
		if (list !== null && list.kind === 'array') {
			return insertIntoBlock(text, list, [JSON.stringify(site.mount)]);
		}
		// kcalc's `extra_dirs` holds only a `worker` key, so the site's own key has to be
		// created rather than appended to. `?? []` at the reading end cannot tell the two
		// states apart, which is why they are separated here and in the check's message.
		return insertIntoBlock(text, extra, [
			`${JSON.stringify(site.projectType)}: [${JSON.stringify(site.mount)}]`,
		]);
	},

	/**
	 * Appends to this package's own `prebuild`, never to a script it shares.
	 *
	 * All four hex-web fronts declare the identical `"prebuild":
	 * "../../common/copy-assets.sh"`, so editing that shell script would run the docs
	 * guard for three sites that have no docs. The append is inside the string literal in
	 * the original bytes, which is what preserves the tabs and the key order that
	 * `JSON.stringify` would not.
	 */
	prebuildHook(text: string | null, site: SiteDescriptor): string | null {
		if (text === null) return null;
		const block = soleBlock(text, 'scripts');
		if (block === null || block.kind !== 'object') return null;
		const fragment = prebuildFragment(site);

		const region = text.slice(block.open, block.close + 1);
		const key = /"prebuild"\s*:\s*"/.exec(region);
		if (key?.index !== undefined) {
			let cursor = block.open + key.index + key[0].length;
			while (cursor < text.length) {
				if (text[cursor] === '\\') {
					cursor += 2;
					continue;
				}
				if (text[cursor] === '"') break;
				cursor += 1;
			}
			if (cursor >= text.length) return null;
			return `${text.slice(0, cursor)} && ${fragment}${text.slice(cursor)}`;
		}
		return insertIntoBlock(text, block, [`"prebuild": ${JSON.stringify(fragment)}`]);
	},

	docsLib(text: string | null): string | null {
		// Created, never rewritten. A file that exists and does not derive is a file
		// somebody wrote, and this module's own header invites that.
		if (text !== null) return null;
		return docsLibModule();
	},

	checkDocsShim(_text: string | null, site: SiteDescriptor): string | null {
		return checkDocsShim(site);
	},

	/**
	 * An insertion, not a round trip.
	 *
	 * A parse and re-serialise was tried and rejected on the output: `JSON.stringify`
	 * puts every array element on its own line, so adding one server reformatted all
	 * three of hex-web's, and the diff of a one-commit file that nobody had touched since
	 * March would have been every line in it. The edit belongs to this package; the rest
	 * of the file belongs to whoever wrote it.
	 */
	mcpJson(text: string | null, site: SiteDescriptor): string | null {
		const entry = mcpServerEntry(site);
		if (text === null) {
			const indent = '\t';
			return (
				'{\n' +
				`${indent}"mcpServers": {\n` +
				`${indent}${indent}"hexdocs": {\n` +
				`${indent}${indent}${indent}"command": ${JSON.stringify(entry.command)},\n` +
				`${indent}${indent}${indent}"args": []\n` +
				`${indent}${indent}}\n` +
				`${indent}}\n` +
				'}\n'
			);
		}
		const block = soleBlock(text, 'mcpServers');
		if (block === null || block.kind !== 'object') return null;
		// A `hexdocs` entry that is present with a different command is somebody's own
		// wiring, and a second key of the same name would be a file that parses to
		// whichever one came last.
		if (/"hexdocs"\s*:/.test(text.slice(block.open, block.close + 1))) return null;
		const indent = entryIndent(text, block);
		const unit = detectIndent(text);
		return insertIntoBlock(text, block, [
			`"hexdocs": {\n${indent}${unit}"command": ${JSON.stringify(entry.command)},\n` +
				`${indent}${unit}"args": []\n${indent}}`,
		]);
	},

	gitignore(text: string | null): string | null {
		const existing = text === null ? '' : withTrailingNewline(text);
		const lines = existing.split('\n').map((line) => line.trim());
		const missing = GITIGNORE_ENTRIES.filter((entry) => !lines.includes(entry));
		if (missing.length === 0) return existing;
		const header = '# Written by `hexdocs install`. Prefetched bundles are build output.';
		return `${existing}${existing === '' ? '' : '\n'}${header}\n${missing.join('\n')}\n`;
	},

	refuse(): string | null {
		return null;
	},
} as const;

// ---------------------------------------------------------------------------
// The instructions the three spreads need, shaped to the consumer in hand
// ---------------------------------------------------------------------------

/**
 * `routes.ts`, and the two consumers need different sentences.
 *
 * hex-web's `PAGES` is a local `[path: string, file: string][]` inside `routes.ts`, so a
 * docs spread joins it. kcalc's `pages()` maps `PAGES` from `lib/pages.ts`, whose
 * elements carry `key`, `path`, `file`, `priority`, `changefreq` and `ground` and whose
 * `key` is a closed ten-member `PageKey` union with an exhaustive `PAGE_SCOPES` record
 * behind it. A docs page cannot join that registry without widening a union in the
 * consumer's own source, so the instruction there declares the docs routes beside the
 * existing mounts instead.
 */
function routesInstruction(site: SiteDescriptor, text: string | null): string {
	const file = joinPosix(site.site, 'app/routes.ts');
	const head = [
		`${file}: add the docs routes, importing DOCS_ROUTES from ./lib/docs:`,
		'',
		'  import { DOCS_ROUTES } from "./lib/docs";',
		'',
		'The machine endpoints must be declared top level, between the bare mount and the',
		'`route(":lang", ...)` call. A leaf route with no default export is dispatched to',
		"`queryRoute`, which runs that route's own loader and no parent's, so one mounted",
		'under `:lang` answers `GET /banana/<base>/llms.txt` with a 200. Their order is',
		'already correct in DOCS_ROUTES and must be preserved: every static suffix comes',
		'before the splat, because a dynamic pattern that scores as a static segment ties',
		'with a real static one and the tie breaks on declaration order.',
		'',
		'  // between `...pages("en/")` and `route(":lang", ...)`:',
		'  ...DOCS_ROUTES.filter((r) => r.kind === "machine").map((r) => route(r.path.slice(1), r.file)),',
		'',
	];

	const tupleShaped =
		text !== null && /PAGES\s*:\s*\[\s*path\s*:\s*string/.test(stripComments(text));
	if (tupleShaped) {
		return [
			...head,
			'  // inside PAGES, which is a [path, file] tuple array here:',
			'  ...DOCS_ROUTES.filter((r) => r.kind === "page").map(',
			'  \t(r) => [r.path.slice(1), r.file] as [string, string],',
			'  ),',
			'',
			'No docs route module may export `headers`. React Router copies only Set-Cookie',
			'from a parent, so a child `headers` export ships docs pages with no',
			'Content-Security-Policy and no nonce, and the page renders and never hydrates.',
		].join('\n');
	}

	return [
		...head,
		'This site maps a page registry rather than a tuple array, and its page key is a',
		'closed union with an exhaustive scope record behind it, so a docs page cannot join',
		'that registry without widening a union in this repository. Declare the docs pages',
		'beside the existing mounts instead:',
		'',
		'  function docsPages(idPrefix: string) {',
		'  \treturn DOCS_ROUTES.filter((r) => r.kind === "page").map((r) =>',
		'  \t\troute(r.path.slice(1), r.file, { id: `${idPrefix}${r.path.slice(1)}` }),',
		'  \t);',
		'  }',
		'',
		'  export default [',
		'  \t...pages("en/"),',
		'  \t...docsPages("en/"),',
		'  \t// the machine spread above goes here',
		'  \troute(":lang", "routes/lang.tsx", [...pages("lang/"), ...docsPages("lang/")]),',
		'  ] satisfies RouteConfig;',
		'',
		'No docs route module may export `headers`. React Router copies only Set-Cookie',
		'from a parent, so a child `headers` export ships docs pages with no',
		'Content-Security-Policy and no nonce. On this site it also drops Vary: Cookie and',
		'the whole cache policy, because that is what the root `headers` export carries.',
	].join('\n');
}

/** `paths.ts`, where one consumer has a spread to join and the other has an alias. */
function localisedPathsInstruction(site: SiteDescriptor, text: string | null): string {
	const file = joinPosix(site.site, 'app/lib/paths.ts');
	const stripped = text === null ? '' : stripComments(text);
	const alias = /export\s+const\s+LOCALISED_PATHS[^=]*=\s*[A-Za-z_$][\w$]*\s*;/.test(stripped);

	if (!alias) {
		return [
			`${file}: add the docs addresses to LOCALISED_PATHS:`,
			'',
			'  import { DOCS_PATHS } from "./docs";',
			'  // inside the LOCALISED_PATHS array:',
			'  \t...DOCS_PATHS,',
			'',
			'root.tsx renders the canonical link and all eight hreflang alternates above the',
			'meta outlet and gates them on this list, and a route can append tags but never',
			'delete them. A docs slug missing from it ships with no canonical and a noindex.',
		].join('\n');
	}

	return [
		`${file}: LOCALISED_PATHS here is an alias of one registry, so there is nowhere to`,
		'add a spread. Concatenate instead:',
		'',
		'  import { DOCS_PATHS } from "./docs";',
		'  export const LOCALISED_PATHS: readonly string[] = [...PAGE_PATHS, ...DOCS_PATHS];',
		'',
		'Adding the docs slugs to the page registry is not the alternative. That registry is',
		'simultaneously the route table, the sitemap source, the lastmod key space and the',
		'i18n scope selector, so an entry there demands a ground, a lastmod key and a scope',
		'prefix per page, and its key is a closed union. The concatenation keeps the',
		"registry's own invariant intact for the pages it owns.",
		'',
		'root.tsx gates the canonical and the eight alternates on this list, so a docs slug',
		'missing from it ships with no canonical and a noindex.',
	].join('\n');
}

/** The sitemap, where one consumer has an `entries` array and the other has none. */
function sitemapInstruction(site: SiteDescriptor, text: string | null): string {
	const file = joinPosix(site.site, 'app/routes/sitemap[.]xml.tsx');
	const stripped = text === null ? '' : stripComments(text);
	const hasEntries = /const\s+entries\b[^=]*=\s*\[/.test(stripped);

	const why = [
		'',
		'DOCS_SITEMAP already excludes hidden pages. A hidden page stays published,',
		'indexable and addressable while staying out of the sidebar, out of prev and next,',
		'and out of the sitemap, and a hand-listed docs spread advertises it to Google.',
	];

	if (hasEntries) {
		return [
			`${file}: derive the docs entries:`,
			'',
			'  import { DOCS_SITEMAP } from "~/lib/docs";',
			'  // inside the entries array:',
			'  \t...DOCS_SITEMAP,',
			...why,
		].join('\n');
	}

	return [
		`${file}: this file has no entries array to spread into. It maps a page registry`,
		'directly, so the docs rows have to be concatenated where the URL list is built:',
		'',
		'  import { DOCS_SITEMAP } from "~/lib/docs";',
		'  const sources = [',
		'  \t...PAGES.map((page) => ({ path: page.path, priority: page.priority, changefreq: page.changefreq })),',
		'  \t...DOCS_SITEMAP,',
		'  ];',
		'',
		'and then map `sources` where `PAGES` was mapped. Docs pages have no lastmod key,',
		'so the lastmod line stays conditional on the lookup, which it already is.',
		...why,
	].join('\n');
}

// ---------------------------------------------------------------------------
// The table
// ---------------------------------------------------------------------------

/**
 * One table per descriptor.
 *
 * Memoised because three of the instructions are shaped to what the consumer's own file
 * looks like, so building the table reads files, and `checks.ts` asks for it once per
 * finding it emits. The cache is keyed on the descriptor object rather than on a path, so
 * a second `detectSite` over the same repository builds a fresh table and re-reads: this
 * is a within-one-run memo and never a cache of the filesystem.
 */
const TABLES = new WeakMap<SiteDescriptor, Edit[]>();

/**
 * Every edit, shaped to the repository in hand.
 *
 * Built per descriptor because half of these need a path computed from it and three need
 * an instruction shaped to what the consumer's own file looks like. The predicates and
 * the appliers are the module-level tables above, so every record carries the same
 * function objects whatever the descriptor, which is what the identity assertion depends
 * on.
 */
export function editsFor(site: SiteDescriptor): Edit[] {
	const cached = TABLES.get(site);
	if (cached !== undefined) return cached;
	const built = buildEdits(site);
	TABLES.set(site, built);
	return built;
}

function buildEdits(site: SiteDescriptor): Edit[] {
	const read = (file: string): string | null => site.files.read(file);
	const routesFile = joinPosix(site.site, 'app/routes.ts');
	const pathsFile = joinPosix(site.site, 'app/lib/paths.ts');
	const sitemapFile = joinPosix(site.site, 'app/routes/sitemap[.]xml.tsx');
	const tsconfigFile = joinPosix(site.site, 'tsconfig.json');

	return [
		{
			id: 'submodule',
			check: 'wiring-submodule',
			file: '.gitmodules',
			present: PRESENT.submodule,
			apply: APPLY.refuse,
			byHand: true,
			// By hand, against the design that had this as a mechanical append. Writing
			// the stanza alone produces a declared submodule with no gitlink, which is a
			// state the check then has to report and which a fresh clone gets nothing
			// from. `git submodule add` writes the stanza, stages the gitlink and creates
			// the checkout in one operation, and it refuses if the path is already in the
			// index, so an append here would also make that command fail.
			instruction: [
				`Add the submodule at ${site.mount}:`,
				'',
				`  git submodule add ${DOCS_REMOTE} ${site.mount}`,
				'',
				'A stanza in .gitmodules is not a committed submodule. The package is consumed',
				'as TypeScript source through a tsconfig paths entry, so there is no install',
				'step that could fail loudly: on a fresh clone the only symptom is a module',
				'resolution error inside the build, naming a path.',
			].join('\n'),
		},
		{
			id: 'workspace-exclusion',
			check: 'wiring-workspace-exclusion',
			file: 'pnpm-workspace.yaml',
			present: PRESENT.workspaceExclusion,
			apply: APPLY.workspaceExclusion,
			instruction: [
				`pnpm-workspace.yaml: add \`  - "!${site.mount}"\`, with the double quotes.`,
				'',
				'A workspace glob enrols the mount as a package, so `pnpm install` inside it',
				'installs this whole monorepo and ignores kit/pnpm-lock.yaml, which is the',
				'lockfile the toolchain is pinned to. The quotes are load-bearing:',
				'apps/front/scripts/check-tools.mjs matches that literal string including them.',
			].join('\n'),
		},
		{
			id: 'tsconfig-paths',
			check: 'wiring-tsconfig-path',
			file: tsconfigFile,
			present: PRESENT.tsconfigPaths,
			apply: APPLY.tsconfigPaths,
			instruction: [
				`${tsconfigFile}: add these to compilerOptions.paths:`,
				'',
				...tsconfigPathEntries(site).map(
					([key, target]) => `  ${JSON.stringify(key)}: [${JSON.stringify(target)}],`,
				),
				'',
				'vite-tsconfig-paths is the only thing turning these into Vite aliases, so',
				'without them tsc and Vite disagree about the same specifier and the failure',
				'arrives as a resolution error inside a submodule during a deploy. Nothing in',
				'the consuming repository builds a dist/, which is why they point at source.',
			].join('\n'),
		},
		{
			id: 'tsconfig-resolve-json',
			check: 'wiring-tsconfig-path',
			file: tsconfigFile,
			present: PRESENT.tsconfigResolveJson,
			apply: APPLY.refuse,
			byHand: true,
			// By hand because on both consumers this option is set in a shared
			// `config/tsconfig.front.json` that other packages extend, and an install
			// scoped to one site has no business editing it.
			instruction: [
				'Set `"resolveJsonModule": true` in the TypeScript configuration this site',
				`extends (${tsconfigFile}, or whichever config it extends).`,
				'',
				'app/lib/docs.ts imports *.docs.json through import.meta.glob, and without',
				'this the typecheck fails on the glob rather than on anything a reader would',
				'connect to the docs install.',
			].join('\n'),
		},
		{
			id: 'deploy-hash-dirs',
			check: 'wiring-deploy-hash-dirs',
			file: 'deploy.config.json',
			present: PRESENT.deployHashDirs,
			apply: APPLY.deployHashDirs,
			instruction: [
				`deploy.config.json: list ${JSON.stringify(site.mount)} in hash.extra_dirs.${site.projectType ?? '<project type>'}.`,
				'',
				'Change detection is hash based over project directories. A submodule that is',
				'not listed leaves the hash identical when the submodule changes, the deploy',
				'reports unchanged, and production keeps serving the old code.',
			].join('\n'),
		},
		{
			id: 'prebuild-hook',
			check: 'wiring-prebuild-hook',
			file: joinPosix(site.site, 'package.json'),
			present: PRESENT.prebuildHook,
			apply: APPLY.prebuildHook,
			instruction: [
				`${joinPosix(site.site, 'package.json')}: append to this package's own prebuild.`,
				'',
				`  ${prebuildFragment(site)}`,
				'',
				'There is no CI on this repository, so a check that only runs when somebody',
				'types it is not a guard. prebuild is the one thing that always runs: the',
				'deploy builds on the host before the Docker build, and the container install',
				"runs with scripts disabled and never repeats it. Append to this package's own",
				'prebuild string and never to a shell script other front packages share.',
			].join('\n'),
		},
		{
			id: 'check-docs-shim',
			check: 'wiring-prebuild-hook',
			file: joinPosix(site.site, 'scripts/check-docs.mjs'),
			present: PRESENT.checkDocsShim,
			apply: APPLY.checkDocsShim,
			instruction:
				'The generated guard shim. It holds no copy of what is checked and is rewritten in full on every install, so a kit upgrade refreshes it.',
		},
		{
			id: 'gitignore',
			check: 'wiring-prebuild-hook',
			file: joinPosix(site.site, '.gitignore'),
			present: PRESENT.gitignore,
			apply: APPLY.gitignore,
			instruction: [
				`${joinPosix(site.site, '.gitignore')}: ignore what hexdocs prefetch writes:`,
				'',
				...GITIGNORE_ENTRIES.map((entry) => `  ${entry}`),
				'',
				'Both trees are build output fetched from a bundle keyed by commit. Committing',
				'them puts a copy of every page in every language into the site repository and',
				'makes every prefetch a diff.',
			].join('\n'),
		},
		{
			id: 'site-config',
			check: 'wiring-localised-paths',
			file: joinPosix(site.site, 'app/docs'),
			present: PRESENT.siteConfig,
			apply: APPLY.refuse,
			byHand: true,
			instruction: [
				`No <project>.docs.json under ${joinPosix(site.site, 'app/docs')}.`,
				'',
				'  hexdocs scaffold site --site <site> --project <project>',
				'',
				'It names the mount point, the sidebar label in seven languages and the',
				'labelled commits, and it is the sole build input the routes, LOCALISED_PATHS,',
				'the hreflang set and the sitemap are all derived from. `hexdocs sync` fills in',
				'its pages array afterwards.',
			].join('\n'),
		},
		{
			id: 'docs-lib',
			check: 'wiring-localised-paths',
			file: joinPosix(site.site, 'app/lib/docs.ts'),
			present: PRESENT.docsLib,
			apply: APPLY.docsLib,
			instruction: [
				`${joinPosix(site.site, 'app/lib/docs.ts')} exists and does not derive its three`,
				'exports from the package, so it was not rewritten: a file that exists and does',
				'not derive is a file somebody wrote. Make it export DOCS_PATHS, DOCS_ROUTES and',
				'DOCS_SITEMAP from docsLocalisedPathsFor, docsRouteRows and docsSitemapRows over',
				'an import.meta.glob of ../docs/*.docs.json, or delete it and run install again.',
			].join('\n'),
		},
		{
			id: 'routes',
			check: 'wiring-routes',
			file: routesFile,
			present: PRESENT.routes,
			apply: APPLY.refuse,
			byHand: true,
			instruction: routesInstruction(site, read(routesFile)),
		},
		{
			id: 'localised-paths',
			check: 'wiring-localised-paths',
			file: pathsFile,
			present: PRESENT.localisedPaths,
			apply: APPLY.refuse,
			byHand: true,
			instruction: localisedPathsInstruction(site, read(pathsFile)),
		},
		{
			id: 'sitemap',
			check: 'wiring-sitemap',
			file: sitemapFile,
			present: PRESENT.sitemap,
			apply: APPLY.refuse,
			byHand: true,
			instruction: sitemapInstruction(site, read(sitemapFile)),
		},
		{
			id: 'mcp-json',
			check: 'wiring-mcp',
			file: '.mcp.json',
			present: PRESENT.mcpJson,
			apply: APPLY.mcpJson,
			instruction: [
				'.mcp.json: add the hexdocs server.',
				'',
				`  "hexdocs": ${JSON.stringify(mcpServerEntry(site))}`,
				'',
				'Without it an agent in this repository has no way to read a page, check a tree',
				'or reach a skill.',
			].join('\n'),
		},
		{
			id: 'mcp-settings',
			check: 'wiring-mcp',
			file: '.claude/settings.json',
			present: PRESENT.mcpSettings,
			apply: APPLY.refuse,
			byHand: true,
			instruction: settingsInstruction(site),
		},
	];
}

/** The one edit an id names, for a test and for a message. */
export function editById(site: SiteDescriptor, id: string): Edit | undefined {
	return editsFor(site).find((edit) => edit.id === id);
}
